### ISSUE TITLE
无法登陆，文字有重影，openSUSE TW +KDE

### ISSUE THREAD

**Issue by PoisonBCat** [gmg137/netease-cloud-music-gtk#1]
使用纯手机号登陆：登陆异常
使用“+86手机号”登陆：登录异常
使用用户名登陆：登陆异常

文字有重影
![Screenshot_20190411_214003](https://user-images.githubusercontent.com/23402397/55962007-a5f0f480-5ca2-11e9-8a05-847d545be9b5.png)

**Comment by gmg137** [comment]
登陆仅支持手机号和邮箱，不需要+86，提示登陆异常可能是网易检测到你在非常用设备登陆或登陆频繁所致，你可以在网页先登陆一下，然后再在客户端登陆试试。

字体重影你可以删除 ~/.NeteaseCloudMusicGtk 后重新打开试试

**Comment by gmg137** [comment]
![2019-04-12 15-01-01 的屏幕截图](https://user-images.githubusercontent.com/6460323/56018160-e8164680-5d33-11e9-9725-d0a47f6dd8e1.png)
重影是因为这几个字中有几个不是UTF-8字符编码导致的。

**Comment by gmg137** [comment]
字体重影问题已修复

**Comment by PoisonBCat** [comment]
十分感谢回复

不过经过再次测试后发现手机号仍然登陆异常
邮箱可以登陆但是账户框无法输入进过长的邮箱如“poisonbcat@163.com”

**Comment by gmg137** [comment]
邮箱长度限制问题已修复，可以下载新版本测试看看。

你可以先在网页版用手机号登陆试试看，我这里用手机号登陆是没问题的。

**Comment by PoisonBCat** [comment]
现阶段已可正常使用，感谢您的工作
