### ISSUE TITLE
上一曲，下一曲，音乐时长

### ISSUE THREAD

**Issue by SaiyanmanJ** [gmg137/netease-cloud-music-gtk#102]
上一曲，下一曲按钮，换得歌不是当前歌单里的歌，选择的是循环播放模式，然后此模式下一首歌放完了，也不会到下一首，而是非本歌单里的一首，我也不知道那哪里的。
音乐时长本来是几分钟，有的会变成10秒左右的歌，用网易云官方的听是正常的。
顺便问一下 osdlyrisc 怎么用，打开但是没检测到netease-cloud-music-gtk的样子，暂时没搜到怎么办。
系统是 manjaro-xfce20.1

**Comment by gmg137** [comment]
在歌单页点右上角播放按钮才是播放该歌单，直接双击只是播放这一首。

osdlyrics 需要单独安装，然后打开netease-cloud-music-gtk设置中的 osdlyrics 歌词选项就可以了。

**Comment by SaiyanmanJ** [comment]
恩，的确是，谢了。刚开始 osdlyrics 没反应，今天用可以了，不知道为啥。
那就只有_音乐时长_的问题了。

**Comment by gmg137** [comment]
清理下缓存试试
```
rm $HOME/.cache/netease-cloud-music-gtk/*.mp3
```

**Comment by SaiyanmanJ** [comment]
真的可以啦。谢谢！！请问知道 osdlyrics 歌词只在前两句循环是咋回事吗（不跟着歌的时间走，显示完作词显示作曲显示作词....循环）？没搜到啊。

**Comment by gmg137** [comment]
是所有歌词都只循环前两句还是只有某一首或几首？

歌词的缓存文件在 $HOME/.lyrics 目录下，可以直接找到相应歌曲的歌词文件看看里边的内容，是否正确，如果不正确直接删除重新播放应该就行了。

________________________________

**Comment by SaiyanmanJ** [comment]
歌词看了，是全的。所有歌词都是只循环前两句。

**Comment by gmg137** [comment]
建议到 osdlyrics 项目下问问，应该是上游的问题。

**Comment by SaiyanmanJ** [comment]
好的，感谢！暂时没啥问题了，关了。

**Comment by SaiyanmanJ** [comment]
[28#](https://github.com/gmg137/netease-cloud-music-gtk/issues/28#issuecomment-529110820)
中提到aur中是老版本的，于是我重新安装了 aur/osdlyrics-git 0.5.5.rc2.r0.g818bac8-1 (+6 0.60)  可以了。哈哈。
