### ISSUE TITLE
任务栏图标如何修改？

### ISSUE THREAD

**Issue by zanpen2000** [gmg137/netease-cloud-music-gtk#104]
![深度截图_选择区域_20201118100318](https://user-images.githubusercontent.com/3360804/99473415-7f6a6380-2985-11eb-9b18-6c978ca8913c.png)

如图，我想修改任务栏图标，不知道如何修改

系统是manjaro，桌面是kde

**Comment by gmg137** [comment]
修改 /usr/share/applications/netease-cloud-music-gtk.desktop ，将里边的 Icon 字段值改为图标的绝对路径。

**Comment by zanpen2000** [comment]
忘了说我直接下载的AppImage版本，环境是manjaro-kde.

您说的方法我这没管用 :(

gmg137 <notifications@github.com> 于2020年11月18日周三 下午12:20写道：

**Comment by heddxh** [comment]
aur 下载的版本也有同样的问题，会 fallback 到默认图标，比如上面的那个 X
将 desktop 文件中的 icon 修改为绝对路径也没用。
桌面环境是 KDE, 系统是 Arch linux
在其他地方显示的图标是正确的并且会随着 desktop 文件更改，只有任务栏/dock图标有问题。

**Comment by gmg137** [comment]
测试下其他gtk4应用是否有此问题，gtk3之后就不支持状态栏了，怀疑是 KDE 的问题。

**Comment by heddxh** [comment]
测试了 gnome 的 nautilus，是正常的，并且遵从了KDE的icon set
以及任务栏图标也和状态栏有关吗？

**Comment by heddxh** [comment]
解决了，是 aur 打包问题。
删除桌面文件`.desktop`中的`StartupWMClass=com.gitee.gmg137.NeteaseCloudMusicGtk4`，或指定为正确的值。
感谢开发这么棒的应用！
