### ISSUE TITLE
Manjaro + xfce 下关闭至后台运行没有 tray icon

### ISSUE THREAD

**Issue by ety001** [gmg137/netease-cloud-music-gtk#105]
Manjaro + xfce 下关闭至后台运行没有 tray icon。

**Comment by gmg137** [comment]
因为gnome取消了托盘，gtk也跟风删除了托盘功能，所以目前后台运行是没有托盘图标的。

替代方案：
1、直接点击程序启动图标。
2、安装支持 Mpris2 的播放插件（不清楚xfce是否支持）。

________________________________

**Comment by ety001** [comment]
原来如此。

我看了下xfce的插件，只有mpd的。

目前按照你给你的方案，安装了 Mpris，然后再托盘里新建了一个启动器，命令为
```
playerctl -p NeteaseCloudMusic play-pause
```

非常感谢！
