### ISSUE TITLE
部分歌单播放按钮失效

### ISSUE THREAD

**Issue by mnixry** [gmg137/netease-cloud-music-gtk#109]
# 基础信息

- 操作系统: Manjaro 20.2.1 KDE Plasma
- 软件版本: 1.2.0 (archlinuxcn源最新)

# 问题描述

![图片](https://user-images.githubusercontent.com/32300164/105621618-7d6cc700-5e44-11eb-98a2-85d3c8cc262d.png)

该歌单播放按钮无法播放 (我感觉是GUI实现的问题)
之前是其他歌单, 这个歌单可以, 非常玄学
加上`--debug`参数也没啥显示

**Comment by gmg137** [comment]
分享下歌单链接，，，，猜测可能是歌单太长网速慢造成加载延迟

**Comment by mnixry** [comment]
> 分享下歌单链接，，，，猜测可能是歌单太长网速慢造成加载延迟

http://music.163.com/playlist/2275363969/397221440/

**Comment by gmg137** [comment]
问题已修复，可以等待下一个版本或用下面的文件替换原程序。
[netease-cloud-music-gtk.zip](https://github.com/gmg137/netease-cloud-music-gtk/files/5871543/netease-cloud-music-gtk.zip)
