### ISSUE TITLE
manjaro gnome打不开

### ISSUE THREAD

**Issue by lt292** [gmg137/netease-cloud-music-gtk#11]
刚装的manjaro 18.04 
安装后有图标 点击无反应
内核版本 4.19.34-1-MANJARO
GNOME Shell 3.32.0

**Comment by lt292** [comment]
命令行报错信息
netease-cloud-music-gtk: /usr/lib/libm.so.6: version `GLIBC_2.29' not found (required by netease-cloud-music-gtk)

**Comment by lt292** [comment]
> 命令行报错信息
> netease-cloud-music-gtk: /usr/lib/libm.so.6: version `GLIBC_2.29' not found (required by netease-cloud-music-gtk)

我看了下我的系统的glibc版本是 2.28-5的稳定版
这个程序是从manjaro的软件包管理器下载的

**Comment by gmg137** [comment]
不要用预编译的包，自己下载源码编译。

**Comment by BruceZhang1993** [comment]
@lt292  Manjaro 还没有升 glibc 2.29  建议从 AUR 手动编译
