### ISSUE TITLE
KDE下媒体播放器控件获取到的专辑图非常糊

### ISSUE THREAD

**Issue by KevinMX** [gmg137/netease-cloud-music-gtk#110]
如图。系统为Arch Linux，安装的是archlinuxcn打包的版本。使用官方版客户端时这个图是清晰的。
![图片](https://user-images.githubusercontent.com/17025286/106140022-2d299800-61a9-11eb-9f12-2e2816081f86.png)

**Comment by gmg137** [comment]
为了节省流量提升加载速度，加载的图片都会小一点。不过你这个应该是因为提前缓存了同名的图片造成的，你可以删除缓存后再重新打开试试。

**Comment by KevinMX** [comment]
> 为了节省流量提升加载速度，加载的图片都会小一点。不过你这个应该是因为提前缓存了同名的图片造成的，你可以删除缓存后再重新打开试试。

尝试清空~/.cache/netease-cloud-music-gtk后还是一样xD
应该是前者了，直接加载的就是小的缩略图。
个人感觉在电脑上节省流量/提升加载速度可能感知不强，毕竟专辑图也就那么大嘛。

**Comment by gmg137** [comment]
刚发现，你这是播放控件中的图片吧?

**Comment by gmg137** [comment]
因为是在GNOME 下测试的，GNOME的播放控件显示的图片很小所以一直没发现这个问题。等我统一下缓存图片大小就可以了。
