### ISSUE TITLE
更完善的 Mpris 支持

### ISSUE THREAD

**Issue by tuberry** [gmg137/netease-cloud-music-gtk#112]
最近想弄个桌面歌词插件，
![2021-02-04 00-22-58 的屏幕截图](https://user-images.githubusercontent.com/17917040/106776642-3ae68e00-667f-11eb-80c0-4d265339f879.png)
发现 `Player:Position` 总是返回零，而 gnome-music 能正常返回:
```
dbus-send --print-reply --type=method_call  --dest=org.mpris.MediaPlayer2.org.gnome.Music /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Position
```
以致人为改变位置或歌词文件加载慢时难以同步时间轴（用 osdlyrics 也存在同样的问题）。希望能有更完善的 [Mpris](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html) 支持，尤其是 `Position`。另，保存的歌词文件名用 `Title-Artist.lrc` 之类的格式（osdlyrics 也支持设置）也许能减少冲突？谢谢。

**Comment by gmg137** [comment]
对 dbus 的运行机制一直不是很熟悉，我已经添加了 Position 支持，但在 osdlyrics 下没有任何效果。下面是新打包的程序，你可以测试下是否能获取到 position 值。

[netease-cloud-music-gtk.zip](https://github.com/gmg137/netease-cloud-music-gtk/files/5922915/netease-cloud-music-gtk.zip)

**Comment by tuberry** [comment]
能取到`Position`（可以用 `d-feet` 看），但是实现方式可能有些问题。我监听 `g-properties-changed` 信号来获取标题、歌手等状态改变。而 `Position` 随时间改变不应该触发该信号否则过于频繁。所以目前测试一播放整个系统就卡死了。而 `gnome-music` 和 `lollypop` 这两播放器都没问题。

**Comment by gmg137** [comment]
现在换了个思路，当移动进度条时才会发送消息。
[netease-cloud-music-gtk.zip](https://github.com/gmg137/netease-cloud-music-gtk/files/5923811/netease-cloud-music-gtk.zip)

**Comment by gmg137** [comment]
时间精确到微秒，并更新歌词文件命名规则。
[netease-cloud-music-gtk.zip](https://github.com/gmg137/netease-cloud-music-gtk/files/5924258/netease-cloud-music-gtk.zip)

**Comment by tuberry** [comment]
确实没有发送过多的消息了，但是返回零:
```
dbus-send --print-reply --type=method_call  --dest=org.mpris.MediaPlayer2.NeteaseCloudMusic /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Position
```
而且不知为什么[同步获取](https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/b22625dd5e033ade507500a2af1fbe900fc3ca53/src/service/components/mpris.js#L717) `Position`导致 gnome-shell 卡顿。而 gnome-music 和 lollypop 以及 vlc 都没有这个问题。

**Comment by gmg137** [comment]
现在只有拖动进度条时才会更新 position 的值，所以会获取 0 。。。我看了 gnome-music 和 lollypop 的源码，没看明白他们的逻辑。

明天我再研究下

**Comment by gmg137** [comment]
现在我这里有两种更新 position 值的方法，一种是随时间实时更新，但这样会造成大量消息的发送。另一种是当拖动进度条时做同步，这种方式需要你能监听到进度条变化，否则获取到的就是过期值。

想知道你测试 gnome-music 时是怎样返回的？需要我这里如何做怎样的处理？

**Comment by tuberry** [comment]
返回方式就是直接调用[dbus](https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/b22625dd5e033ade507500a2af1fbe900fc3ca53/src/service/components/mpris.js#L720)，和用终端差不多。 position 值在 dbus 里是只读的而且不会触发 `g-properties-changed`。所以我觉得这个值并不需要实时更新到 dbus，只需在 dbus 调用 get 方法时返回此时的 position 就行。

**Comment by gmg137** [comment]
你这样应该不能能实现同步播放进度，当我拖动进度条的时候你这里应该监听 mpris 的 seek事件，不然你怎么确定调用get的时机？

**Comment by tuberry** [comment]
就轮询啊。歌词随时间重绘更新时获取 position 。差不多同步就行

**Comment by gmg137** [comment]
这样设计不太好，应该是我直接按时间同步position值，你在收到消息后可以计算间隔，如果小于阈值比如500ms则不更新歌词。。。你可以研究下osdlyrics是怎么实现的，轮循肯定不是好主意。

妙行无住，自在于心

________________________________

**Comment by tuberry** [comment]
我不知道 osdlyrics 怎么实现的。我的做法就是不断刷新重画，每次获取 postion 比不用 position 定个计时器 cpu 占用会低一点，但占用主要和刷新频率相关。或许结合起来可以优化一下吧。

**Comment by gmg137** [comment]
感觉直接监听 mpris2 的 postion 或 seek 事件会更简单，有变化时再重绘，没变化就按歌词文件中的时间往前推进。

**Comment by tuberry** [comment]
只要音乐不暂停 position 就一直在变化，歌词也要相应地重绘。经过前面的尝试监听 position 不可行，监听 seeked 也许可以解决拖动进度条的问题。但是还有加载延迟在那，我知道切歌了需要从文件里加载歌词，没有还得从网上下，这中间的几百毫秒不是固定的。所以我至少需要知道拖动进度后的位置和我歌词准备好时的位置。总之，无论我如何实现通过 dbus 获取 position 的方法是少不了的。至于每次获取 position 还是自己设个 timer 我尝试了觉着性能差距不大，至于难易程度前者还少个监听。

****
不管我的看法或做法如何，Mpris 按 gnome-music 或 lollypop 的实现来总应该没问题。

**Comment by gmg137** [comment]
我现在有点迷，理论上我应该跟随播放时间实时更新 position 的值，但这样做你会因为收到的消息过多而卡死。我看了 gnome-music 和 lollypop 的源码，没有找到单独修改 position 的地方，所以我现在很好奇他们是如何更改 position 的同时而不触发改动信号的。

**Comment by tuberry** [comment]
我粗略看了下 [gnome-music](https://gitlab.gnome.org/GNOME/gnome-music/-/blob/master/gnomemusic/mpris.py) 和 [lollypop](https://gitlab.gnome.org/World/lollypop/-/blob/1.2.26/lollypop/mpris.py) 的 mpris 确实没有特别处理 position。但看他们的 `PropertiesChanged`信号，我觉得应该从控制信号发射这方面入手。没有必要在 pisition 自然变更时发，只需要调用 get 时返回即可。

**Comment by gmg137** [comment]
找到问题所在了，上游的 Mpris2 包在修改 position 时会发送信号。我改了他的源码你试试是否可行。
[netease-cloud-music-gtk.zip](https://github.com/gmg137/netease-cloud-music-gtk/files/5931372/netease-cloud-music-gtk.zip)

PS: 因为涉及上游变更，这个问题可能需要等上游修复后才能真正解决。

**Comment by tuberry** [comment]
不知道 rust 怎么实现的，访问 position 平均算来和 python 比居然有一个数量级的差距。每 300ms 也没取的必要了。
![图片](https://user-images.githubusercontent.com/17917040/107021234-da6e6280-67de-11eb-9716-bbebdbdc293b.png)

**Comment by gmg137** [comment]
看上游的源码是250ms轮询一次。

妙行无住，自在于心

________________________________

**Comment by tuberry** [comment]
也许是惯例，gnome-music 和 lollypop 自己实现弄的`mpris`，读取快读到的`position`也能用。而 vlc 读取也快但是读到的posiiton是跳变的想来里面也是有个间隔轮询来着。就这样吧。
劳烦你一直改，谢谢了。

**Comment by tuberry** [comment]
编译尝试了一下发现还是获取 position 为0也收不到 seeked 信号。不确定是不是我环境的问题，插件在[desktop-lyric](https://github.com/tuberry/desktop-lyric)。

**Comment by gmg137** [comment]
上游的 mpris 库还没有修复，我这里暂时把 position 更新的部分注释了，所以你获取到的还是0。不过 seek 信号应该可以收到才对。。。。我安装你的插件测了下，在更新 plsition 的情况下歌词还是没有变化。

**Comment by tuberry** [comment]
我 DBus 接口里去除了 Position，所以 position 改变插件应该不会收到信号了。另外我监听的 Seeked 信号用 gnome-music 或者 Lollypop 或是官方的网易云（有时候无效）测试都是有效的。但 netease-cloud-music-gtk 收不到这信号。

**Comment by gmg137** [comment]
我尝试直接调用方法发送 "Seeked" 信号，歌词还是没有反应，你可以调试下看是否有发出该信号。
[netease-cloud-music-gtk.zip](https://github.com/gmg137/netease-cloud-music-gtk/files/6019115/netease-cloud-music-gtk.zip)

**Comment by tuberry** [comment]
没有收到信号，我加了一句log，[desktop-lyric_v4.zip](https://github.com/gmg137/netease-cloud-music-gtk/files/6019236/desktop-lyric_v4.zip)，用`gnome-extensions install desktop-lyric_v4.zip` 安装重启 gnome shell 后，`journalctl -f -o cat /usr/bin/gnome-shell` 查看日志（图里是 lollypop 的输出）:
![lol](https://user-images.githubusercontent.com/17917040/108650887-91671f80-74fb-11eb-83f3-51294dc47349.png)

**Comment by gmg137** [comment]
查了下是因为上游没有发送 Seeked 信号的方法，已经提交PR，不确定什么时候能正式合并。
[netease-cloud-music-gtk.zip](https://github.com/gmg137/netease-cloud-music-gtk/files/6019910/netease-cloud-music-gtk.zip)

**Comment by tuberry** [comment]
谢谢，seeked 有效了。

------

是 mpris-player 这个上游啊， 他的 [SetPosition](https://gitlab.gnome.org/World/Rust/mpris-player/-/blob/master/src/mpris_player.rs#L230) 实现好像和[标准](https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Method:SetPosition)不一样。该方法标准里特意带个 trackId 预防竞态而他这没有，而且 position 改变是[不应该](https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Property:Position)发信号的而他这发。实际上位置改变是有个专门的 Seeked 信号的。不过我现在接口里没用 Position，我取消注释了你实时更新进度的代码编译运行测试没有问题，可以获取 position 也不存在卡顿。

**Comment by tuberry** [comment]
[NCM api](https://github.com/gmg137/netease-cloud-music-api) Mpris 歌曲多个歌手只返回一个不太合理，相关[issue](https://github.com/tuberry/desktop-lyric/pull/15#issuecomment-1435716008)。

**Comment by gmg137** [comment]
单靠歌曲名和歌手名不管怎么匹配都还是无法避免出错，如果能通过歌曲ID来匹配是最好的。

话说我在重构到 2.0 后 desktop-lyric 就不能用了，没有任何显示，是我这边的问题吗?

**Comment by tuberry** [comment]
> 单靠歌曲名和歌手名不管怎么匹配都还是无法避免出错，如果能通过歌曲ID来匹配是最好的。

歌曲ID的确好但它不在 Mpris 的 metadata 中，只有根据歌曲+歌手搜索ID再获取歌词。仅提供一个歌手无法精确匹配多个歌手的情况。

> 话说我在重构到 2.0 后 desktop-lyric 就不能用了，没有任何显示，是我这边的问题吗?

我这 NCM-Gtk4 2.2.0 / Gnome Shell 44 / Arch  除了多歌手歌曲由于上述原因没有显示别的正常。如果其他播放器（如Lollypop）能用可能是旧版本插件检测音乐播放器有问题。可以从 Github 安装改下 shell-version 支持版本试试。

**Comment by gmg137** [comment]
@tuberry 我可以把歌曲ID 添加到 metadata 的 track_number,这样你就可以直接通过歌曲ID来匹配了。

**Comment by tuberry** [comment]
> @tuberry 我可以把歌曲ID 添加到 metadata 的 track_number,这样你就可以直接通过歌曲ID来匹配了。

好是好但 `xesam:trackNumber` 专用于表示歌曲在trackList中的位置，复用别的恐怕也不妥。其实有歌名+歌手(s)+专辑基本够用了。

**Comment by poly000** [comment]
> > @tuberry 我可以把歌曲ID 添加到 metadata 的 track_number,这样你就可以直接通过歌曲ID来匹配了。
> 
> 好是好但 `xesam:trackNumber` 专用于表示歌曲在trackList中的位置，复用别的恐怕也不妥。其实有歌名+歌手(s)+专辑基本够用了。

我在其他播放器拉pr改得都是 `xesam:url` 或者 `mpris:trackid`

**Comment by poly000** [comment]
> 找到问题所在了，上游的 Mpris2 包在修改 position 时会发送信号。我改了他的源码你试试是否可行。 [netease-cloud-music-gtk.zip](https://github.com/gmg137/netease-cloud-music-gtk/files/5931372/netease-cloud-music-gtk.zip)
> 
> PS: 因为涉及上游变更，这个问题可能需要等上游修复后才能真正解决。

我看了一下 MPRIS2 spec
> The org.freedesktop.DBus.Properties.PropertiesChanged signal is not emitted when this property changes. 
上游现在有没有正确处理？

**Comment by poly000** [comment]
> 找到问题所在了，上游的 Mpris2 包在修改 position 时会发送信号。我改了他的源码你试试是否可行。 [netease-cloud-music-gtk.zip](https://github.com/gmg137/netease-cloud-music-gtk/files/5931372/netease-cloud-music-gtk.zip)
> 
> PS: 因为涉及上游变更，这个问题可能需要等上游修复后才能真正解决。

https://github.com/Mange/mpris-rs/blob/d74e182d548cbf295c079659bfa78fbdc917305c/src/generated/media_player_player.rs#L106
看起来上游并不会发信号啊……

**Comment by tuberry** [comment]
目前 2.3.0 中`Position` 和 `Seeked` 都已支持，我想这个问题算解决了。

> 我在其他播放器拉pr改得都是 `xesam:url` 或者 `mpris:trackid`
> 
> Feeluown: fuo://`<PLATFORM>`/`<ID>` YesPlayMusic / Qcm / ElectronNCM: /..../ID

谢谢，这两个确实更好些。总的来说，支持更广泛的用例性价比更高，就像上面提到的歌手不全的问题要专门支持也容易，但用其他播放器时难免产生重复文件，这对不支持 dedup 的文件系统不太友好。我这儿需求是歌词而取`songId`出于无奈，所以更[倾向](https://github.com/tuberry/desktop-lyric/issues/17#issuecomment-1829030298)于[`xesam:asText`](https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#xesam:astext)。

**Comment by poly000** [comment]
> 目前 2.3.0 中`Position` 和 `Seeked` 都已支持，我想这个问题算解决了。
> 
> > 我在其他播放器拉pr改得都是 `xesam:url` 或者 `mpris:trackid`
> > Feeluown: fuo://`<PLATFORM>`/`<ID>` YesPlayMusic / Qcm / ElectronNCM: /..../ID
> 
> 谢谢，这两个确实更好些。总的来说，支持更广泛的用例性价比更高，就像上面提到的歌手不全的问题要专门支持也容易，但用其他播放器时难免产生重复文件，这对不支持 dedup 的文件系统不太友好。我这儿需求是歌词而取`songId`出于无奈，所以更[倾向](https://github.com/tuberry/desktop-lyric/issues/17#issuecomment-1829030298)于[`xesam:asText`](https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#xesam:astext)。

原来有字段可以提供歌词
格式是？单句还是LRC

**Comment by tuberry** [comment]
看描述里的复数形式以及 xseam 下的其他字段，我认为这是个常量（LRC）。如果是单句的话需要频繁更新metadata，不太合理。
