### ISSUE TITLE
GNOME环境下音量异常问题

### ISSUE THREAD

**Issue by matrikslee** [gmg137/netease-cloud-music-gtk#122]
系统是Archlinux，桌面环境是GNOME（目前是GNOME40,没升级之前也有问题）

在软件中设置音量和在GNOME系统设置中调节音量是不同步的，比例差了很多，
例如在软件中把音量调节到了最低下一格，在系统中还有一半的音量，但是如果软件中将音量调成0，系统中也会变成0。
如果在系统中单独设置软件的音量，则不会反馈到软件中来。
从用户角度来说，这个问题还是蛮影响体验的。

GNOME用的应该都是pulseaudio服务。
我之前用的音频服务是pulseaudio,现在换成了pipewire，pipewire下用的是pipewire-pulse兼容pulseaudio，不过都有问题。

请问这个问题有计划修复吗？如果需要我可以提供一些帮忙（如提供调试信息等）

**Comment by gmg137** [comment]
测了下，其它使用 pulseaudio 服务播放音乐的应用也会出现音量条不同步的问题，应该是 GNOME 本身的问题。

**Comment by matrikslee** [comment]
啊这样，那就得找GNOME报告bug了 xD，那我先关掉这个issue了
