### ISSUE TITLE
希望播放时打开播放列表时可以自动定位到当前正在播放的音乐

### ISSUE THREAD

**Issue by YuziO2** [gmg137/netease-cloud-music-gtk#128]
如果播放列表和选歌列表都能有定位按钮就好了

**Comment by gmg137** [comment]
感觉意义不大，播放条显示的永远是正在播放的歌曲，上一曲下一曲直接通过播放条切换就行了。通常打开播放列表肯定不是为了找正在播放的歌曲，只可能是当前播放的歌曲不合心意，既然要找的不是当前播放的歌曲，那么定位到它又有什么意义呢？

**Comment by Yuzi19** [comment]
> 感觉意义不大，播放条显示的永远是正在播放的歌曲，上一曲下一曲直接通过播放条切换就行了。通常打开播放列表肯定不是为了找正在播放的歌曲，只可能是当前播放的歌曲不合心意，既然要找的不是当前播放的歌曲，那么定位到它又有什么意义呢？

啊，因为本人一直用的是红心歌单随机播放，有的时候听到喜欢的IP就像去听其他这个IP的歌，所以有这个需求

**Comment by gmg137** [comment]
同一个IP是啥意思？

**Comment by Yuzi19** [comment]
> 同一个IP是啥意思？

额，就是同一个专辑的歌吧，一个专辑的红心我都是一起点的

**Comment by gmg137** [comment]
目前还不支持搜索专辑，所以就算你找到歌曲所在的专辑，也还是没办法找到同专辑的歌曲。最近比较忙，也许以后也添加相关功能。
