### ISSUE TITLE
How about a termnial version?

### ISSUE THREAD

**Issue by FrontMage** [gmg137/netease-cloud-music-gtk#13]
Terminal version is way cooler!

**Comment by gmg137** [comment]
已经有人开发基于 python 的终端版本，之前一直在用这个。
[musicbox](https://github.com/darknessomi/musicbox)

**Comment by FrontMage** [comment]
> 已经有人开发基于 python 的终端版本，之前一直在用这个。
> [musicbox](https://github.com/darknessomi/musicbox)

Python is very slow and panics all the time...

**Comment by wi24rd** [comment]
> Python is very slow and panics all the time...

你是要倍速播放吗（手动滑稽

**Comment by gmg137** [comment]
已经有人做了: https://github.com/betta-cyber/netease_music_api
