### ISSUE TITLE
无法完全显示歌单名

### ISSUE THREAD

**Issue by sun-rongyang** [gmg137/netease-cloud-music-gtk#132]
非常感谢作者开发这个项目。

在 Manjaro KDE 下面有左侧歌单名无法显示全的问题，无法拖动歌单窗口使其变宽。系统信息和应用显示情况见如下截图。
![system-info](https://user-images.githubusercontent.com/20738314/126420378-f1e63532-6897-4765-9ddd-fbff6d0fd2f9.png)
![Screenshot from 2021-07-21 10 15 26](https://user-images.githubusercontent.com/20738314/126420447-1be4218e-39fa-4a1e-85da-e51a138bb1ad.png)

**Comment by gmg137** [comment]
这是故意设计成这样的，因为测试时候发现有些专辑名长度太随意了，长的可以达到50多个字符。如果要看完整的专辑名可以点击后，查看右边显示的专辑名。

**Comment by sun-rongyang** [comment]
> 这是故意设计成这样的，因为测试时候发现有些专辑名长度太随意了，长的可以达到50多个字符。如果要看完整的专辑名可以点击后，查看右边显示的专辑名。

哦 原来如此 非常感谢！
