### ISSUE TITLE
Add to Flathub

### ISSUE THREAD

**Issue by catsout** [gmg137/netease-cloud-music-gtk#133]
Hi,
I submitted netease-cloud-music-gtk to Flathub to install it as a flatpak package.  

https://github.com/flathub/flathub/pull/2486

**Comment by catsout** [comment]
There is a [metainfo file](https://github.com/flathub/flathub/pull/2486/files#diff-3fbcd93fc13aceaf9ddfa564ec2be47420b75a7bd66edb6c96762f74b90f2c62), which determined the info show on flathub page like [typora](https://flathub.org/apps/details/io.typora.Typora)  
Please tell me any thing that needs to be changed.

**Comment by catsout** [comment]
When the pr merged, it will create a repo on flathub organization, like https://flathub.org/apps/details/io.typora.Typora.  
This repo's any commit will make flathub update(recompile) your package.   
You can get the repo permission anytime.

**Comment by gmg137** [comment]
Hi, thanks a lot, there is nothing in the mateinfo file that needs to be changed.

**Comment by catsout** [comment]
@gmg137 
Do you consider maintain flatpak version yourself?  
It's recommend by flathub, and I also think so.  
It's hard for me to update flatpak version with a lot change different from upstream version.  

You can use https://github.com/flatpak/flatpak-builder-tools/tree/master/cargo to generate sources to build app offline which is required by flathub.  
You can go flathub's matrix group to ask more details.
