### ISSUE TITLE
密码位数是否有限制？

### ISSUE THREAD

**Issue by Novite5** [gmg137/netease-cloud-music-gtk#136]
用网易邮箱登录，反复显示“登录异常”。我的密码位数比较长，有二十多位，这是否是原因？

谢谢您的辛勤开发和分享！

**Comment by gmg137** [comment]
密码位数没有限制，你可以先在浏览器登陆下，因为使用的web接口，经常会有异地登陆验证导致登陆异常。

**Comment by Novite5** [comment]
试了一下，原来是网易云音乐的网页端对密码有限制。

谢谢您的回复！
