### ISSUE TITLE
请求升级为 GTK4 + libadwaita

### ISSUE THREAD

**Issue by Paraworker** [gmg137/netease-cloud-music-gtk#141]
GTK4感觉性能好多了，libadwaita界面也很好看哈哈

**Comment by gmg137** [comment]
有考虑过，不过现在许多发行版应该都还没包含 GTK4，计划等 GNOME 升 GTK 4了我再跟进。

**Comment by Paraworker** [comment]
可能要等到 GNOME 42 吧，不过用了 Flatpak 也就没有为每个发行版打包的必要了吧

**Comment by wineee** [comment]
> 有考虑过，不过现在许多发行版应该都还没包含 GTK4，计划等 GNOME 升 GTK 4了我再跟进。

如果有时间的话，可以先在 dev 分支更新，让能用gtk4的先用上

**Comment by gmg137** [comment]
已重构
