### ISSUE TITLE
Support for different languages

### ISSUE THREAD

**Issue by kalikiana** [gmg137/netease-cloud-music-gtk#142]
Hello,

I wonder if you'd consider support for localization. As far as I can see there's no translation currently. Since Netease works well for me e.g. in Germany the app is nice to have. But it is a little like poking in the dark to see what happens because I can't read anything.

**Comment by gmg137** [comment]
No plans for the time being, localisation support is not expected to be added until the gtk4 refactoring.

**Comment by gmg137** [comment]
Localization support has been added in version 2.0.
