### ISSUE TITLE
请问还会更新吗

### ISSUE THREAD

**Issue by Revincx** [gmg137/netease-cloud-music-gtk#143]
项目距离上一次维护已经半年了，请问作者是否还会继续维护这个项目呢？

很喜欢这个网易云的客户端，使用起来比其他的都要流畅，希望能继续更新！

**Comment by gmg137** [comment]
当前版本功能上不会再有大的更新了，最多适配下上流接口变动。。。以后也许会用GTK4重构一把，也许...

**Comment by yyy33** [comment]
> 当前版本功能上不会再有大的更新了，最多适配下上流接口变动。。。以后也许会用GTK4重构一把，也许...

请问为什么最新版没有appimage了
