### ISSUE TITLE
上架 deepin/UOS 商店请求

### ISSUE THREAD

**Issue by Hibanaw** [gmg137/netease-cloud-music-gtk#148]
应用投递方式参见：
https://old.deepin.wiki/index.php?title=%E6%B7%B1%E5%BA%A6%E5%95%86%E5%BA%97:%E5%BA%94%E7%94%A8%E6%8A%95%E9%80%92

**Comment by gmg137** [comment]
deepin 上有官方版网易云，感觉上架意义不大。
