### ISSUE TITLE
播放 Hi-res 音频时，输出频率限制为 48KHz

### ISSUE THREAD

**Issue by h0cheung** [gmg137/netease-cloud-music-gtk#149]
测试可用专辑：[Soaring (96 Khz)](http://music.163.com/#/m/album?id=38664597)

测试环境：fedora 36 Workstation

使用 pipewire-pulse，已修改其配置，允许各个常见频率输出，官方网易云客户端（加了通过 LD_PRELOAD 使用系统 vlc 的 patch）可以正常以 96KHz 输出。

**Comment by gmg137** [comment]
搜了下 gstreamer 应该是有 bug 不支持 96khz 的采样率。

**Comment by h0cheung** [comment]
> 搜了下 gstreamer 应该是有 bug 不支持 96khz 的采样率。

可以考虑用 vlc-rs 播放吗，我尝试过自己替换，但是由于对 rust 不熟悉，没有跑起来

**Comment by gmg137** [comment]
目前和rust绑定最好的就是gstreamer，有官方支持维护，其次是ffmpeg。vlc目前没有好的绑定库，vlc-rs已经4年没更新了。

**Comment by gmg137** [comment]
目前和rust绑定最好的就是gstreamer，有官方支持维护，其次是ffmpeg。vlc目前没有好的绑定库，vlc-rs已经4年没更新了。

**Comment by gmg137** [comment]
今天看了下下载下来的音乐，直接就是 48khz的，不确定是不是vip才能听96khz。
```
558997038.mp3: Audio file with ID3 version 2.4.0, contains: MPEG ADTS, layer III, v1, 128 kbps, 48 kHz, Stereo
```

你手头要是有96khz 音乐的话可以发我一份，我在本地测下看 gstreamer 能不能正常播放。

**Comment by h0cheung** [comment]
我用另一个使用 gstreamer 的软件（GNOME Videos，用 C 编写的）播放是 96KHz，不排除 API 存在问题，有方便的方法抓取本项目播放的音频文件吗？

**Comment by gmg137** [comment]
你设置里有没有把音质设成最高？

音乐都缓存在 ~/.cache/netease-cloud-music-gtk4 目录下，你可以在里边按音乐id找一下，看缓存下来的是不是flac格式。如果不是的话就把之前的mp3文件删除，重新登陆后再播放试试。

**Comment by gmg137** [comment]
由于每次播放都是播放的缓存文件，所以播放flac之类比较大的文件等待时间会长一些。缓存完成后才会开始播放。

**Comment by h0cheung** [comment]
无论怎么设置，下载的音乐都是 mp3，而且每次重启本软件都会丢失登录状态，可能 cookie 部分有问题。

不确定是不是发行版差异、打包导致的问题，正在尝试调试（我使用的发行版是 fedora workstation 36），[打包文件](https://download.copr.fedorainfracloud.org/results/nyepi/nyepi/fedora-36-x86_64/04582419-netease-cloud-music-gtk/netease-cloud-music-gtk.spec)（作者不是我，但我有在此基础上维护的打算）

**Comment by h0cheung** [comment]
用付费音乐测试（曲库中支持到 SQ），未登录时播放为 30s，登录后可以播放，看来 cookie 在不重启时是工作的。但播放码率始终为 320 kbps，无论选 HR 还是 SQ，应该 API 部分有问题。

**Comment by gmg137** [comment]
由于上游库限制，目前还无法保存登陆状态。。。明天我看下，由于没有会员所以一些vip功能都没有做测试。

**Comment by gmg137** [comment]
确实是我代码问题，起初是把设置码率写在最上边api初始化的地方，后来考虑每次请求都要读取设置会有性能损耗，就把设置码率移到下载的地方而且没做测试😅
