### ISSUE TITLE
Readme 文档问题

### ISSUE THREAD

**Issue by zhangzp9970** [gmg137/netease-cloud-music-gtk#15]
在readme文档中，打包安装一节说的是git clone git@github.com:gmg137/netease-cloud-music-gtk.git，这样做使用ssh从github下载需要您的密钥，应该使用https下载，所以应改为git clone https://github.com/gmg137/netease-cloud-music-gtk.git

**Comment by gmg137** [comment]
已经修正，不过这并不需要下载我的密钥，而是取决于你是否在 github 绑定你的 ssh 公钥。

**Comment by zhangzp9970** [comment]
好的，谢谢
