### ISSUE TITLE
为什么不继续提供 deb 包了？

### ISSUE THREAD

**Issue by KaguYuuki** [gmg137/netease-cloud-music-gtk#158]

**Comment by gmg137** [comment]
提供deb并不能解决所有deb系的兼容，建议向相关发行版的官方源或中文源维护组申请加入该软件支持。

**Comment by atzlinux** [comment]
解决 deb 系的兼容，有些技巧，对 deb 包的制作有些要求。

请问原来的 deb 打包代码， debian 目录还在吗？ 

我有时间看看

**Comment by gmg137** [comment]
@atzlinux 之前的deb包是从rpm转的😅

**Comment by atzlinux** [comment]
铜豌豆软件源 12 版本 制作了一个支持 Debian 12 的 deb 包：

https://www.atzlinux.com/allpackages-x86_64-v12.htm

大家添加铜豌豆软件源后，可以直接安装使用：

apt install netease-cloud-music-gtk

**Comment by gmg137** [comment]
已添加 ppa 源
