### ISSUE TITLE
选择不发出 Notification

### ISSUE THREAD

**Issue by ksqsf** [gmg137/netease-cloud-music-gtk#16]
切换歌曲的时候似乎会发一条通知，但是 GNOME Shell 本身就有 MPRIS 支持，所以发出这一条通知不仅没有通知意义，还会打扰用户，建议删去，或者提供配置项可以选择不通知。

**Comment by gmg137** [comment]
切换歌曲只会在应用内提示，并不会发送系统通知。。。如果你是配合 osdlyrics 使用，请确认 osdlyrics 的系统通知选项已关闭。

**Comment by ksqsf** [comment]
的确是 OSD Lyrics 发的，抱歉。
