### ISSUE TITLE
不绑定 ctrl + A 快捷键打开信息面板

### ISSUE THREAD

**Issue by JadeVane** [gmg137/netease-cloud-music-gtk#161]
目前版本中，按下 `ctrl` + `A` 快捷键会打开介绍软件信息的关于面板，而且在输入框中也会触发，所以导致在搜索歌曲时，如果希望删掉已输入的搜索关键词再重新输入，那么按下 `ctrl` + `A` 并不会全选已输入的内容，而会打开关于面板，导致每次按下 `ctrl` + `A` 后，都需要用额外用鼠标关掉弹窗，再一个个删掉关键词，增加操作成本。

同时，软件信息并不是常用功能，所以希望可以去除此绑定关系。

**Comment by gmg137** [comment]
建议直接按两次 “/” 或 ctrl+s 来代替删除操作。

**Comment by JadeVane** [comment]
按两次 `/` 是通过关闭再打开搜索框实现清空，确实可以解决问题，但这是一种迂回的解决办法了，你是想要把这个打开面板的功能绑定到这个快捷键上吗？这是出于什么考虑呢？因为 `ctrl` + `A` 确实比关闭再打开搜索框更符合操作习惯

**Comment by gmg137** [comment]
在英文界面 ctrl+a 是取的 About 首字母作为快捷键，算是一种习惯吧。不过你的提议也不错，后边可以改一下。
