### ISSUE TITLE
获取验证码失败无法登陆

### ISSUE THREAD

**Issue by Taoiy** [gmg137/netease-cloud-music-gtk#163]
应用内提示获取验证码失败，然后给了重复的验证码，使用这个验证码登陆失败。
而且后台高频请求music.163.com

![Capture+_2022-08-21-17-27-41(1).png](https://s2.loli.net/2022/08/21/BJXjQLIAe5h8KZ7.png)
![2022-08-21_17-35.png](https://s2.loli.net/2022/08/21/7DidpACGtFbeg3X.png)

**Comment by Taoiy** [comment]
才发现是有扫码登陆的，但是验证码一直没有加载出来

**Comment by gmg137** [comment]
我这里测试所有功能正常，你可以再试下，最近更新 curl 后感觉出了点问题。

**Comment by Taoiy** [comment]
重新测试了，还是同样的问题。贴个软件版本您看一下

>  ~  pacman -Qi curl                                                                                                                                                        ok | at 11:20:13 
> 名字           : curl
> 版本           : 7.84.0-2
> 描述           : An URL retrieval utility and library
> 架构           : x86_64
> URL            : https://curl.haxx.se
> 软件许可       : MIT
> 组             : 无
> 提供           : libcurl.so=4-64
> 依赖于         : ca-certificates  brotli  libbrotlidec.so=1-64  krb5  libgssapi_krb5.so=2-64  libidn2  libidn2.so=0-64  libnghttp2  libpsl  libpsl.so=5-64  libssh2  libssh2.so=1-64
>                  openssl  zlib  zstd  libzstd.so=1-64
> 可选依赖       : 无
> 依赖它         : appstream  cfitsio  cmake  cryfs  exiv2  fcitx5-chinese-addons  fwupd  git  google-earth-pro  gst-plugins-bad  keepassxc  lib32-curl  libcmis  libelf  libgphoto2
>                  libqalculate  libreoffice-fresh  networkmanager  onedrive-abraunegg  openpmix  pacman  pkgfile  poppler  qemu-block-curl  qemu-tools  raptor  rust  sane  steam  tpm2-tss
> 被可选依赖     : apache  fio  mariadb  systemd
> 与它冲突       : 无
> 取代           : 无
> 安装后大小     : 1867.71 KiB
> 打包者         : Christian Hesse <eworm@archlinux.org>
> 编译日期       : 2022年07月08日 星期五 15时02分35秒
> 安装日期       : 2022年07月09日 星期六 21时56分19秒
> 安装原因       : 作为其他软件包的依赖关系安装
> 安装脚本       : 否
> 验证者         : SHA-256 校验值
> 

>  ~  pacman -Qi netease-cloud-music-gtk4                                                                                                                                    ok | at 11:20:20 
> 名字           : netease-cloud-music-gtk4
> 版本           : 2.0.1-3
> 描述           : Linux 平台下基于 Rust + GTK4 开发的网易云音乐播放器
> 架构           : x86_64
> URL            : https://github.com/gmg137/netease-cloud-music-gtk
> 软件许可       : GPL3
> 组             : 无
> 提供           : 无
> 依赖于         : libadwaita  gst-plugins-base
> 可选依赖       : gst-plugins-bad: extra media codecs [已安装]
>                  gst-plugins-good: extra media codecs [已安装]
>                  gst-plugins-ugly: extra media codecs [已安装]
> 依赖它         : 无
> 被可选依赖     : 无
> 与它冲突       : 无
> 取代           : 无
> 安装后大小     : 5.17 MiB
> 打包者         : lilac (on behalf of zttt183525594) <zttt183525594@gmail.com>
> 编译日期       : 2022年07月09日 星期六 20时17分43秒
> 安装日期       : 2022年08月22日 星期一 11时18分33秒
> 安装原因       : 单独指定安装
> 安装脚本       : 否
> 验证者         : SHA-256 校验值

**Comment by Taoiy** [comment]
> 我这里测试所有功能正常，你可以再试下，最近更新 curl 后感觉出了点问题。

已回复

**Comment by gmg137** [comment]
你是所有界面都没有加载到数据还是只有登陆二维码没有加载出来?

**Comment by Taoiy** [comment]
只是登录验证码，应该是后端请求有些问题。

gmg137 ***@***.***> 于 2022年8月22日周一 12:00写道：

**Comment by gmg137** [comment]
刚更新了日志，你从源码编译下，运行时加: RUST_LOG=debug，把日志输出贴出来。

**Comment by Taoiy** [comment]
> 刚更新了日志，你从源码编译下，运行时加: RUST_LOG=debug，把日志输出贴出来。

刚刚手动编译了一下，发现可以用了，不清楚是不是软件源打包那边的问题。

**Comment by gmg137** [comment]
我把另一个 api 请求的库也更新了，估计就是 curl 的问题。

**Comment by Taoiy** [comment]
> 我把另一个 api 请求的库也更新了，估计就是 curl 的问题。

感谢,我手动编译并替换了主程序文件，已经可以使用了，只是收藏的歌单不知道为什么少了一个。btw，ui做的很漂亮
