### ISSUE TITLE
无法加载任何内容

### ISSUE THREAD

**Issue by GongT** [gmg137/netease-cloud-music-gtk#164]
面只有几个按钮，动态内容全都没有加载，包括登陆扫码。

试过设置代理，结果完全一样，从代理服务器的日志看，所有请求似乎都成功了（有上传有下载，字节数也很正常），但界面上就是一片空白。       
发送手机验证码，界面上显示发送失败，但验证码确实收到了。输入后登陆还是失败。

设置了`RUST_LOG=debug`环境，启动程序，依然没有看到任何输出。

尝试从源码运行，但是失败了，不知道该怎么办了（

-----

手动编译在meson前面少一步
```bash
cargo build
```

rhel上的编译依赖：
```bash
dnf install -y rust-gstreamer-player-devel rust-gstreamer-audio-devel rust-gstreamer-base-devel rust-gstreamer-devel libadwaita-devel gtk4-devel gdk-pixbuf2-devel dbus-devel rust meson
```

`ninja install`后运行`netease-cloud-music-gtk4` 输出
```bash

(netease-cloud-music-gtk4:334441): GLib-GIO-ERROR **: 17:57:38.426: Settings schema 'com.gitee.gmg137.NeteaseCloudMusicGtk4' is not installed
追踪与中断点陷阱 (核心已转储)
```

**Comment by GongT** [comment]
之前用的1.x版本，也没有更新过，突然就这样了，然后发现有2.x，更新以后发现一样。

不知道和系统设置有什么关系。（主要是没有日志。。

rpm和flatpak版本都一样。

**Comment by gmg137** [comment]
curl 的问题，最新版本已经修复，稍后打包上传。

**Comment by GongT** [comment]
大佬好快！

**Comment by GongT** [comment]
每日推荐、收藏单曲还是不太正常（

**Comment by gmg137** [comment]
> 每日推荐、收藏单曲还是不太正常（

我试了下，这两个功能都正常没有问题，你可以试下从命令行运行，加 RUST_LOG=debug 打印日志看看。
