### ISSUE TITLE
新增本地账户

### ISSUE THREAD

**Issue by demolg** [gmg137/netease-cloud-music-gtk#17]
目前只能登陆在线账户，没有登陆不能进行收藏，建立歌单等操作。如果能支持登录-本地用户就好

**Comment by gmg137** [comment]
最初有计划本地播放、下载、收藏等功能，但考虑到与“云音乐”的理念相背，便将相关功能取消了。

**Comment by zhourongdong** [comment]
没有个人那一栏，登录完也没有

**Comment by gmg137** [comment]
@zhourongdong 请描述清楚问题，也可以配上截图
