### ISSUE TITLE
音量问题

### ISSUE THREAD

**Issue by wrb2012** [gmg137/netease-cloud-music-gtk#177]
用的rpm安装：
 1.每次开启应用，音量为0；
 2.按+ 号总是100%音量，调节音量只能靠滑杆。

系统：Linux Mint 21 Vanessa
5.17.0-1018-oem #19-Ubuntu SMP PREEMPT Wed Sep 21 09:54:58 UTC 2022

**Comment by gmg137** [comment]
1、默认音量就是0，就是这么设计的。
2、程序没有+号控制音量的快捷键，你应该是触发了系统的音量快捷键。

**Comment by gmg137** [comment]
2.1.0 版本已添加默认音量设置。
