### ISSUE TITLE
歌曲播放错误以及配置文件无法正确修改的问题

### ISSUE THREAD

**Issue by ghost** [gmg137/netease-cloud-music-gtk#18]
1.歌曲无法播放，并报如下错误：（图）
2.在设置里更改了选项后（如最小化到托盘，选项无法改回（即使按钮显示关闭，但点击关闭窗口按钮依然最小化到托盘）

![Screenshot from 2019-04-27 20-01-01](https://user-images.githubusercontent.com/30102054/56865970-ae695f00-6a06-11e9-83ef-ba7c83d9a0ea.png)

**Comment by gmg137** [comment]
1、请确认是所有都无法播放还是偶尔，前者应该是你缺少gstreamer插件，后者可能是因为网易获取的歌曲mp3地址是有过期时间的，大概15分钟左右，不过我会自动重新获取，如果依旧失败就会停止播放，直到你重新点播放按钮。
2、关闭到托盘要重启才会生效。右键托盘图标或点菜单键中的关闭按钮。
