### ISSUE TITLE
实现了歌词吗？

### ISSUE THREAD

**Issue by biluohc** [gmg137/netease-cloud-music-gtk#2]

**Comment by gmg137** [comment]
有歌词接口，但没有写界面(感觉没必要)。如果需要歌词可以安装 osdlyrics（默认许多歌词可能找不到），后续我可以添加适配 osdlyrics 的歌词功能。

**Comment by gmg137** [comment]
@biluohc 已完成 osdlyrics 歌词适配


![2019-04-23 14-44-19 的屏幕截图](https://user-images.githubusercontent.com/6460323/56563152-909e9300-65dd-11e9-938d-ba9a2da53289.png)
