### ISSUE TITLE
分享音乐

### ISSUE THREAD

**Issue by mokurin000** [gmg137/netease-cloud-music-gtk#217]
链接/id 为最优先
另附 歌名，歌手...（支持自定义格式？）

底部分享按钮/歌单右键菜单加上剪贴板读写

**Comment by gmg137** [comment]
这功能感觉用的不多，添加右键菜单太麻烦，我加到播放栏的歌曲名上边了，点击歌曲名就会复制歌曲信息，自己悄悄用吧。
