### ISSUE TITLE
播放私人FM的时候不会自动更新列表

### ISSUE THREAD

**Issue by NEOVALI** [gmg137/netease-cloud-music-gtk#222]
播放私人FM的时候不会自动更新播放列表，播完20首就自动暂停了。

目前只能提前在私人FM那里提前拉好要播的几十首再播，这样略显麻烦

**Comment by gmg137** [comment]
网易的这个 FM 接口一次只返回3首歌曲，你每次下拉其实我是申请了十次接口，总之很不好用，后边可能会取消FM功能

**Comment by NEOVALI** [comment]
如果不好用就阉割掉功能是真的很没意思，本来我听网易云也就听个私人fm
