### ISSUE TITLE
请求增加切换语言功能

### ISSUE THREAD

**Issue by elio-zhy** [gmg137/netease-cloud-music-gtk#223]
**Is your feature request related to a problem? Please describe.**
我的系统默认语言是英文，但是英文界面的排版不是很美观，并且我没有在设置中找到修改语言的功能。

![2022-12-11_13-03](https://user-images.githubusercontent.com/30508272/206887619-774bc9f1-b455-4617-86a0-26762f022a13.png)

**Describe the solution you'd like**
希望能在设置中增加修改语言的功能，或者修改配置文件以修改语言。

**Comment by gmg137** [comment]
修改 desktop 文件，在执行命令前添加：LANG=zh_CN，或命令行启动添加该环境变量也行

**Comment by elio-zhy** [comment]
好的，感谢

**Comment by elio-zhy** [comment]
在 Manjaro Linux 22.0.0 下测试发现添加环境变量 LANG=zh_CN 会提示：
```
Gtk-WARNING **: 14:57:26.192: Locale not supported by C library.
        Using the fallback 'C' locale.
```
修改为 LANG=zh_CN.UTF-8 后仍然为英文。

可以添加环境变量 LANGUAGE=zh_CN，测试有效。
修改 desktop 文件可以使用 `env` 命令，将 desktop 文件中 Exec 修改为：
```
env LANGUAGE=zh_CN netease-cloud-music-gtk4
```
具体参考ArchLinux Wiki [desktop_entries#Modify_environment_variables](https://wiki.archlinux.org/title/desktop_entries#Modify_environment_variables)
