### ISSUE TITLE
gnome43 ibus输入问题

### ISSUE THREAD

**Issue by mrbruce516** [gmg137/netease-cloud-music-gtk#226]
**Describe the bug**
gnome43 ibus输入问题

**Expected behavior**
在搜索歌曲页面功能等，ibus输入可以正常显示复选框

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chrome
 - Version 108.0.5359.124

**Comment by gmg137** [comment]
是不可以正常曲复选框吗?   请确认是否在所有 gtk4 应用下都有该问题还是单单这一个应用。另外确认下是否已安装 ibus-gtk4 包。

**Comment by mrbruce516** [comment]
![image](https://user-images.githubusercontent.com/46187947/209447935-a172d702-98e4-495f-9fca-d52f8e925ec5.png)
没有找到ibus-gkt4这个包，gtk4应用(还有一个是newsflash)确实ibus都有问题。
目前gtk3的程序正常，

**Comment by gmg137** [comment]
到 arch 论坛提问看看，应该就是缺少 ibus-gtk4 包造成的。或者直接更换 fcitx 输入法。
