### ISSUE TITLE
Lag on Arch Linux

### ISSUE THREAD

**Issue by perqin** [gmg137/netease-cloud-music-gtk#23]
All operations requiring network is laggy, such as launching, playing a song and switching to Discover tab. No errors reported in standard output. OS: Latest Arch Linux.

**Comment by gmg137** [comment]
每天第一次打开会缓存首页歌单，发现歌单也会在初次打开时缓存，之后再打开将不会有延迟，播放列表缓存每日自动清理，图片缓存每周自动清理。播放延迟可以打开网页版云音乐，看速度是否正常，并检查网络与DNS配置。

**Comment by perqin** [comment]
> 每天第一次打开会缓存首页歌单，发现歌单也会在初次打开时缓存，之后再打开将不会有延迟，播放列表缓存每日自动清理，图片缓存每周自动清理。播放延迟可以打开网页版云音乐，看速度是否正常，并检查网络与DNS配置。

"Laggy" means UI not responsive. The network is connected. It is strange that it worked properly on my personal computer, but being laggy on my work computer, though both computers have latest Arch Linux installed. I will compile and run it locally to dig into this issue sometime.

**Comment by perqin** [comment]
Is it caused by running network operations on UI thread? I'm new to Rust and can't figure it out.

**Comment by gmg137** [comment]
为了防止 UI 阻塞，所有网络请求都是在独立线程中进行的。理论上网络请求不会造成 UI 无响应。

**Comment by novload** [comment]
网络极为糟糕的情况下会导致界面无响应，包括在运行程序之后和私人FM换歌之后，我猜可能是`download_img`的问题。

**Comment by gmg137** [comment]
> 网络极为糟糕的情况下会导致界面无响应数十秒，包括在运行程序之后和私人FM换歌之后，我猜可能是`download_img`的问题。

download_img 确实是同步执行的，因为 gtk 不支持异步加载图片。虽然可以在独立线程中下载完后再刷新页面，不过这样的网速听歌肯定也会成为问题。全部图片不超过 200k，默认播放 320k 的音乐在 3M 左右。这个问题无解。
