### ISSUE TITLE
libgstplay-1.0 missing

### ISSUE THREAD

**Issue by cloudy-sfu** [gmg137/netease-cloud-music-gtk#239]
**Describe the bug**

I cannot start the program after it's installed, which says

```
netease-cloud-music-gtk4: error while loading shared libraries: libgstplay-1.0.so.0: cannot open shared object file: No such file or directory
```

Where to get this dynamic library?

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Browser: Google Chrome
 - Version: v2.2.0

**Comment by gmg137** [comment]
`sudo apt install gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
      gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
      gstreamer1.0-libav`

**Comment by cloudy-sfu** [comment]
```
sudo apt install gstreamer1.0-plugins-base gstreamer1.0-plugins-good \ gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \ gstreamer1.0-libav
```
Errir:
```
E: Unable to locate package  gstreamer1.0-plugins-bad
E: Unable to locate package  gstreamer1.0-libav
```
Maybe your `\` means choosing one from the two, so I tried
```
sudo apt install gstreamer1.0-plugins-base gstreamer1.0-plugins-good
sudo apt install gstreamer1.0-plugins-ugly
```
Successfully installed.

However, Netease music still has the same problem.

**Comment by gmg137** [comment]
Try this
`apt install gst-plugins-bad gst-plugins-good gst-plugins-base gstreamer`

**Comment by cloudy-sfu** [comment]
```
E: Unable to locate package gst-plugins-bad
E: Unable to locate package gst-plugins-good
E: Unable to locate package gst-plugins-base
E: Unable to locate package gstreamer
```
