### ISSUE TITLE
BUG: cannot  start app

### ISSUE THREAD

**Issue by Jar-36** [gmg137/netease-cloud-music-gtk#243]
**Describe the bug**
This app cannot start on ubuntu18.04.6(amd64)

**To Reproduce**
BASH$ netease-cloud-music-gtk4 
netease-cloud-music-gtk4: error while loading shared libraries: libgstplay-1.0.so.0: cannot open shared object file: No such file or directory

**Expected behavior**
I have installed openssl gstreamer1.0-gtk3 gstreamer1.0-plugins-base gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 18.04.6(amd64)
 - App version: 2.2.0

**Comment by gmg137** [comment]
Ubuntu 18.04 used to be old and is no longer compatible after version 2.0.
