### ISSUE TITLE
Flathub上的项目要更新啦

### ISSUE THREAD

**Issue by nsfoxer** [gmg137/netease-cloud-music-gtk#246]
截止当前（2023年08月13日），flathub上的[版本](https://flathub.org/apps/com.github.gmg137.netease-cloud-music-gtk)为2.1.0,而github的版本为2.2.0。请麻烦作者抽时间更新一下flatpak的包。
![图片](https://github.com/gmg137/netease-cloud-music-gtk/assets/32675834/7da52192-1832-4d04-97d0-ca25da39809f)

**Comment by gmg137** [comment]
flathub上的版本不是我在维护
