### ISSUE TITLE
增加CI?

### ISSUE THREAD

**Issue by huangjj27** [gmg137/netease-cloud-music-gtk#25]
提供在各个环境中构建所需要的依赖的参考, 因进行自动化测试

**Comment by gmg137** [comment]
已添加

**Comment by huangjj27** [comment]
为什么我看不到在哪有构建状态或CI配置文件？ 是不是我少检查了什么配置文件？

**Comment by gmg137** [comment]
理解错了，以为你是要编译依赖的参考。编译依赖已添加到 README，CI 自动测试没弄过，欢迎贡献提 pr。
