### ISSUE TITLE
let .lyrics follow XDG Base Directory specification or user configurable

### ISSUE THREAD

**Issue by test482** [gmg137/netease-cloud-music-gtk#264]
**Is your feature request related to a problem? Please describe.**
This software uses ~/.lyrics to store lyrics instead of using XDG compliant directories, e.g. $XDG_CACHE_HOME $XDG_STATE_HOME.

but data dir, config dir, cache dir are following specification:

```
[2023-12-21T08:47:00Z DEBUG netease_cloud_music_gtk4::path] 初始化数据目录: "/home/user/.local/share/netease-cloud-music-gtk4"
[2023-12-21T08:47:00Z DEBUG netease_cloud_music_gtk4::path] 初始化配置目录: "/home/user/.config/netease-cloud-music-gtk4"
[2023-12-21T08:47:00Z DEBUG netease_cloud_music_gtk4::path] 初始化缓存目录: "/home/user/.cache/netease-cloud-music-gtk4"
[2023-12-21T08:47:00Z DEBUG netease_cloud_music_gtk4::path] 初始化歌词目录: "/home/user/.lyrics"
```

**Describe the solution you'd like**
default use `~/.cache/netease-cloud-music-gtk4/lyrics` to store lyrics. and provides an option to select the location of the lyrics folder.

**Describe alternatives you've considered**
at least provides an option maybe?

**Additional context**
https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories

**Comment by gmg137** [comment]
歌词放置在 ~/.lyrics 是为了默认与osdlyrics等桌面歌词软件兼容，尽可能做到开箱即用。

**Comment by test482** [comment]
下载 osdlyrics 试了下，似乎并没有开箱即用呀 0.0，netease-cloud-music-gtk 自动下载的歌词名称格式为 `%t-%p-%a` （歌曲名-歌手-专辑.lrc），例如 `Hymn For The Weekend-Coldplay-A Head Full of Dreams.lrc`，而 `archlinuxcn/osdlyrics-git 1:0.5.15.r0.g4000dcb-1` 安装后默认配置中歌词文件名检索不包括 `%t-%p-%a`，会一直提示无适配歌词；手动添加 `%t-%p-%a` 之后可以了。


> 歌词放置在 ~/.lyrics 是为了默认与osdlyrics等桌面歌词软件兼容，尽可能做到开箱即用。

osdlyrics 确实是默认检索 ~/.lyrics，用户不想修改的话，的确是开箱即用。

但是用户想修改歌词文件夹保存目录的话， osdlyrics 提供了选项可以添加其他目录，netease-cloud-music-gtk 这边就没有选项可供修改了。

**Comment by gmg137** [comment]
osdlyrics的配置在项目说明中有提及。gnome 有个桌面歌词插件 desktop-lyrics，首选推荐使用这个插件。歌词位置和格式也是专门对其做的适配，使用歌名-歌手-专辑可以最大限度的防止歌词冲突。

另外如果目录变成可随意选择的，对flatpak打包怕也会产生影响，因为需要绑定固定的目录才行。

**Comment by test482** [comment]
> osdlyrics的配置在项目说明中有提及。gnome 有个桌面歌词插件 desktop-lyrics，首选推荐使用这个插件。歌词位置和格式也是专门对其做的适配，使用歌名-歌手-专辑可以最大限度的防止歌词冲突。

~~我本身不用桌面歌词~~，所以没看到项目说明里 osdlyrics 的配置说明

> 另外如果目录变成可随意选择的，对flatpak打包怕也会产生影响，因为需要绑定固定的目录才行。

既然这样，那先 close 了；希望以后考虑支持。
