### ISSUE TITLE
标题栏太宽了

### ISSUE THREAD

**Issue by madoka773** [gmg137/netease-cloud-music-gtk#266]
![image](https://github.com/gmg137/netease-cloud-music-gtk/assets/85693457/ceeefd1c-a0c1-4393-a5a6-d0a2cdaf7f1d)
用gnome-console做了个对比

**Comment by gmg137** [comment]
这是被中间菜单栏挤的，你看看gnme-music，应该也是这么宽。

**Comment by madoka773** [comment]
> 这是被中间菜单栏挤的，你看看gnme-music，应该也是这么宽。

![IMG_20240101_220600.jpg](https://github.com/gmg137/netease-cloud-music-gtk/assets/85693457/920543bc-9204-4ae5-85b3-0de8b74a3512)

并不是

**Comment by gmg137** [comment]
问题已修复，查了下是之前一次合并外部提交时引入的，你要不说的话我竟然一直没发现这个问题。
