### ISSUE TITLE
Ubuntu安装依赖错误

### ISSUE THREAD

**Issue by willyiam84** [gmg137/netease-cloud-music-gtk#270]
**Describe the bug**

依赖错误，如下

**To Reproduce**

<pre><font color="#4E9A06"><b>william@NERV-MAGI</b></font>:<font color="#3465A4"><b>~</b></font>$ sudo apt install netease-cloud-music-gtk
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 netease-cloud-music-gtk : 依赖: libadwaita-1-0 (&gt;= 1.0.1) 但无法安装它
                           依赖: libc6 (&gt;= 2.34) 但是 2.31-0ubuntu9.14 正要被安装
                           依赖: libgdk-pixbuf-2.0-0 (&gt;= 2.22.0) 但无法安装它
                           依赖: libgstreamer-plugins-bad1.0-0 (&gt;= 1.22.0) 但是 1.16.3-0ubuntu1.1 正要被安装
                           依赖: libgtk-4-1 (&gt;= 4.0.0) 但无法安装它
                           依赖: libssl3 (&gt;= 3.0.0) 但无法安装它
<font color="#CC0000"><b>E: </b></font>无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
<font color="#4E9A06"><b>william@NERV-MAGI</b></font>:<font color="#3465A4"><b>~</b></font>$ sudo apt install --fix-broken
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 14 个软件包未被升级。
<font color="#4E9A06"><b>william@NERV-MAGI</b></font>:<font color="#3465A4"><b>~</b></font>$ sudo apt install libadwaita-1-0 libc6 libgdk-pixbuf-2.0-0 libgstreamer-plugins-bad1.0-0 libgtk-4-1 libssl3
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
没有可用的软件包 libgtk-4-1，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到

没有可用的软件包 libssl3，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到

没有可用的软件包 libgdk-pixbuf-2.0-0，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到

没有可用的软件包 libadwaita-1-0，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到

<font color="#CC0000"><b>E: </b></font>软件包 libadwaita-1-0 没有可安装候选
<font color="#CC0000"><b>E: </b></font>软件包 libgdk-pixbuf-2.0-0 没有可安装候选
<font color="#CC0000"><b>E: </b></font>软件包 libgtk-4-1 没有可安装候选
<font color="#CC0000"><b>E: </b></font>软件包 libssl3 没有可安装候选
</pre>

**Desktop:**
 - OS: Ubuntu 20.04

**Screenshots**

![image](https://github.com/gmg137/netease-cloud-music-gtk/assets/62928261/3de67617-c6ba-45c5-87ab-80fad8c0b69c)

**Additional context**
发生在成功添加铜豌豆源之后

**Comment by gmg137** [comment]
20.04 太老了，你需要自己编译下

**Comment by yxw820603** [comment]
同有依赖问题，我的系统是xubuntu 22.04,也是发生在成功添加铜豌豆源之后，我这里报告的是：
`netease-cloud-music-gtk : Depends: libgstreamer-plugins-bad1.0-0 (>= 1.22.0) but 1.20.3-0ubuntu1.1 is to be installed`
20.04应该也不算老啊，毕竟也是LTS版.
希望能够处理下。

自己编译也不是不行，安装编译的工具依赖还得400+M。。这个软件小的优势就完全体现不出来了。
另外flatpak的打包我也试了，软件本身小但是要下载的依赖（我不知道flatpak这种是不是叫做依赖），要超过1G。

**Comment by gmg137** [comment]
22.04 依赖可以直接忽略看看是否有影响，20.04已经是4年前的版本了，那时候GTK4刚发布多半是不支持的。

目前各发行版都是由社区自行维护打包的，按理说ubuntu是比较火的但国内好处一直没人打包进官方源，等我有空了研究了下看能不能自己打包个源。

**Comment by yxw820603** [comment]
22.04,忽略依赖强行安装，运行没有问题。
没时间就不建议弄deb的打包了。
但是建议搞个AppImage的打包。所有的依赖都在一个文件里，体积可能大了点但是依赖问题就很省心。

**Comment by gmg137** [comment]
已添加Ubuntu PPA源，建议通过PPA安装。
