### ISSUE TITLE
编译时发现少了两个依赖

### ISSUE THREAD

**Issue by nan-mu** [gmg137/netease-cloud-music-gtk#276]
编译时发现少了两个依赖，建议将README.md更新以下：

95 + sudo apt-get install -y libssl-dev meson rustc libgtk-4-dev libadwaita-1-dev libgstreamer-plugins-bad1.0-dev **libdbus-1-dev cmake**

**Comment by gmg137** [comment]
在 README 的编译依赖中有dbus, 由于各发行版对包的命名不统一，没办法一一列出，加之能去自己编译的基本都是有一定折腾能力的，解决个依赖应该是小问题。

**Comment by nan-mu** [comment]
原来是这样😯
