### ISSUE TITLE
Fedora安装提示缺少依赖

### ISSUE THREAD

**Issue by Kenxu2022** [gmg137/netease-cloud-music-gtk#277]
我注意到已有一个PR解决这个问题：https://github.com/gmg137/netease-cloud-music-gtk/pull/126  
但在从release下载并安装最新版的时候依然会提示  
```
错误：
 问题: 冲突的请求
  - nothing provides gstreamer needed by netease-cloud-music-gtk-2.3.1-44.1.x86_64 from @commandline
  - nothing provides gstreamer-plugins-base needed by netease-cloud-music-gtk-2.3.1-44.1.x86_64 from @commandline
  - nothing provides gstreamer-plugins-good needed by netease-cloud-music-gtk-2.3.1-44.1.x86_64 from @commandline
(尝试添加 '--skip-broken' 来跳过无法安装的软件包)
```
需要使用`sudo rpm -i ./netease-cloud-music-gtk-2.3.1.x86_64.rpm --nodeps`强制绕过依赖  

系统：Fedora 39 Workstation

**Comment by Kenxu2022** [comment]
另外，这次的更新似乎没有发布flatpak包，flathub上也没有相应的更新

**Comment by gmg137** [comment]
目前默认提供的rpm包是openSUSE Tumbleweed 版本的，如果依赖版本低可以试试 [openSUSE Leap 15.6/15.5](https://software.opensuse.org/download/package?package=netease-cloud-music-gtk&project=multimedia%3Aapps) 的包，记得下载相应的语言包。

PS：最好的解决方案是到fedora中文社区提需求，让他们打包进官方源里。

flathub 上的包是[第三方](https://github.com/flathub/com.github.gmg137.netease-cloud-music-gtk)在维护，如果有flatpak版本的需求可以去其[项目](https://github.com/flathub/com.github.gmg137.netease-cloud-music-gtk)下提issue。
