### ISSUE TITLE
有提供查看歌词翻译的功能吗

### ISSUE THREAD

**Issue by acyanbird** [gmg137/netease-cloud-music-gtk#278]
现在使用 osdlyric 和直接点击查看的歌词只有原文，可以提供网易云的歌词翻译吗？这是已经实现只是需要特殊设置还是没有实现呢？期待回答，谢谢了！

**Comment by gmg137** [comment]
目前还没有实现该功能，回头研究下看是否有公开的可用接口。

**Comment by acyanbird** [comment]
好的，谢谢您的回复！
