### ISSUE TITLE
Archlinux，osdlyrics好像获取不到播放进度

### ISSUE THREAD

**Issue by qlmlove** [gmg137/netease-cloud-music-gtk#28]
歌词的前两句一直在循环播放，但是不播放后边的歌词，命令行debug模式启动osdlyrics报下边错误

```bash
*Error*: in function ol_dbus_list_names: ol_utils_dbus.c[421]
assert connection != NULL failed
*Error*: in function ol_dbus_list_names: ol_utils_dbus.c[421]
assert connection != NULL failed
Error in connection() 111 - 拒绝连接
Error in connection() 111 - 拒绝连接
```

**Comment by gmg137** [comment]
如果音乐正常播放，那就是 osdlyrics 的锅。或者换个支持 mpris 的音乐播放器试试看歌词正常不

**Comment by qlmlove** [comment]
@gmg137 VLC播放的时候歌词正常，不过既然大佬把锅让 osdlyrics  背了，那我就凑活凑活听歌吧，哈哈，歌词也没什么

**Comment by gmg137** [comment]
有问题还是要解决的，请尝试以下方法:
1、检查歌词文件是否下载完整。
2、到 osdlyrics 的 issues 提交错误，看上边的错误是什么意思。
3、自己动手编译 netease-cloud-music-gtk 运行看是否正常。

**Comment by BruceZhang1993** [comment]
@qlmlove 
目前 osdlyrics 正在使用 Python 重构，所以目前官方源的 osdlyrics 已经是很老的版本了
建议尝试下 https://aur.archlinux.org/packages/osdlyrics-python3-git 这个包

![image](https://user-images.githubusercontent.com/6873988/64475879-ee153400-d1ba-11e9-84dc-dc5eca2d3c16.png)
