### ISSUE TITLE
希望添加当前歌词高亮显示

### ISSUE THREAD

**Issue by XilongYang** [gmg137/netease-cloud-music-gtk#280]
如题，现在歌词是纯文本显示，很难一眼定位到当前唱的位置。希望可以加入一个当前歌词的强调显示。
![image](https://github.com/gmg137/netease-cloud-music-gtk/assets/47446800/132a9213-f660-4b25-9310-05142eb5ab65)
![image](https://github.com/gmg137/netease-cloud-music-gtk/assets/47446800/ee71b2b6-fd08-4e31-be98-de4f9d2824c5)

**Comment by gmg137** [comment]
已添加
