### ISSUE TITLE
gtk4版本启动失败

### ISSUE THREAD

**Issue by ad2248** [gmg137/netease-cloud-music-gtk#285]
**Describe the bug**
程序无法启动

**To Reproduce**
1. 打开终端
2. 输入netease-cloud-music-gtk4
3. 报错 
``` 
thread 'main' panicked at src/main.rs:46:14:
Could not load resources: Error { domain: g-file-error-quark, code: 4, message: "Failed to open file “/home/gmg/projects/netease-cloud-music-gtk/__build/host/share/netease-cloud-music-gtk4/netease-cloud-music-gtk4.gresource”: open() failed: No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
**Expected behavior**
正常启动

**Screenshots**
![image](https://github.com/gmg137/netease-cloud-music-gtk/assets/57805906/de43bbd7-8093-4d81-960c-59cbb6be511d)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux trixie/sid 
 - 桌面: KDE

**Comment by gmg137** [comment]
我又重新打包了一个，你再试试: https://github.com/gmg137/netease-cloud-music-gtk/releases/download/2.4.0/netease-cloud-music-gtk4_2.4.0-1_amd64.deb
