### ISSUE TITLE
fedora 编译 找不到libopenssl-devel

### ISSUE THREAD

**Issue by stokhos** [gmg137/netease-cloud-music-gtk#29]
fedora 没有这个libopenssl-devel 没有这个依赖，cargo rpm build失败。rpm包直接安装报没有gstreamer-player，也不能安装。

**Comment by gmg137** [comment]
各个linux发行版对包的命令不太一样，在 fedora 下 libopenssl-devel 的名称应该是 openssl-devel。

gstreamer-player 的问题请确认以下包是否已经安装:  
```
gstreamer1-plugins-good, gstreamer1-plugins-ugly, gstreamer1-plugins-base, gstreamer1-plugins-bad
```

**Comment by stokhos** [comment]
openssl-devel,  gstreamer1*都装了
还是不行

error: Failed build dependencies:
	libopenssl-devel is needed by netease-cloud-music-gtk-0.6.0-1.x86_64
error: rpmbuild error: error running /usr/bin/rpmbuild (exit status: exit code: 1)

**Comment by gmg137** [comment]
修改项目.rpm目录下的打包脚本，把 BuildRequires: libopenssl-devel 改成 openssl-devel

**Comment by stokhos** [comment]
改称openssl-devel可以，但是还是Requires: gstreamer-plugins-libav 这个包，fedora也没有，删除这行可以安装，但是好像播放有问题。

**Comment by gmg137** [comment]
安装 gstreamer1-libav，系统源没有的话就是在 rpmfusion 里。

**Comment by stokhos** [comment]
额，还是播放失败，可能是因为我在国外
