### ISSUE TITLE
首页大面积空白，疑似Banner图没有展示出来

### ISSUE THREAD

**Issue by stairclimber** [gmg137/netease-cloud-music-gtk#291]
**Describe the bug**
应用首页上半部分空白，且存在控件混乱情况，疑似Banner图没有加载出来。如下图所示。

**To Reproduce**
在下文环境中打开即可复现。

**Expected behavior**
首页应该正确显示图片和控件

**Screenshots**
![image](https://github.com/user-attachments/assets/e2fa0f00-8da9-4e0d-86e5-5b932c9304df)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 LTS
 - Browser chrome
 - Version 127.0.6533.99

**Additional context**
应用安装自flatpak官方仓库flathub，安装命令为
flatpak install com.github.gmg137.netease-cloud-music-gtk

$ uname -a
Linux ubuntu 6.8.0-40-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 10:34:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

**Comment by gmg137** [comment]
轮播图因为上游接口变了，早就修复了， 还没发布，需要验证下新接口的稳定性

**Comment by stairclimber** [comment]
> 轮播图因为上游接口变了，早就修复了， 还没发布，需要验证下新接口的稳定性

了解了，感谢回复，感谢你开发开源软件，netease music gtk 很好用！

**Comment by gmg137** [comment]
修复版已发布，可通过ppa或flathub更新。
