### ISSUE TITLE
KDE Wayland 下拖拽歌词闪退

### ISSUE THREAD

**Issue by Arom1a** [gmg137/netease-cloud-music-gtk#303]
**To Reproduce**
1. 播放歌曲、打开歌词
2. 选中歌词
3. 左键歌词并拖动
4. 程序崩溃

**Screenshots**
https://github.com/user-attachments/assets/4ea06fe9-f732-422d-a54a-f055ebe987fe

**Desktop (please complete the following information):**
 - OS: 6.10.10-arch1-1 (64-bit)
 - KDE Plasma Version: 6.1.5
 - KDE Frameworks Version: 6.6.0
 - QT Version: 6.7.2
 - Graphics Platform: Wayland
 - Netease Cloud Music Gtk4 Version: 2.3.1 

**Additional context**
None

**Comment by Arom1a** [comment]
才发现有新版本，但是我没有办法编译安装 #304

**Comment by gmg137** [comment]
在gnome桌面环境下无法复现该问题，你可以安装 gtk4-devel-tools，然后在终端运行 gtk4-demo, 程序启动后运行其中的 "Text View"->"Hypertext"，再试下拖动文本的操作看会崩溃不会。

**Comment by Arom1a** [comment]
2.4.1版本已修复，不会闪退了
