### ISSUE TITLE
建议优化一下退出程序的逻辑

### ISSUE THREAD

**Issue by imzf** [gmg137/netease-cloud-music-gtk#31]
当正在播放音乐时，关闭窗口时程序并不退出而是进入后台。当在前台程序，点击暂停播放按钮，暂停播放音乐时，关闭窗口时完全退出程序

**Comment by gmg137** [comment]
这样可能会跟全局的关闭到后台在语义上产生冲突，不好处理。

**Comment by xz-dev** [comment]
建议关闭窗口后，可以在状态栏显示相关图标及其播放状态

**Comment by gmg137** [comment]
@xz-dev 因为GNOME 3 取消系统托盘，GTK 3也不再提供相关方法，所以目前无法实现托盘功能。

对于你的需求，在GNOME下可以通过通知栏查看、控制播放状态以及唤醒程序。KDE右下角好像也有一个显示多媒体状态的区域具有相同功能。

**Comment by xz-dev** [comment]
GNOME 可以使用 [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/) 继续使用系统托盘
另外，我认为悬浮窗也许是一个良好的解决方法（类似于网易云音乐 Linux 版本）

**Comment by gmg137** [comment]
其实 0.7 版本前是有托盘的，后来更新gtk依赖发现相关控件被删除无法编译，只能将相关功能去除，目前还没有找到在 gtk3 实现托盘图标的方法。

**Comment by gmg137** [comment]
[托盘图标问题请看这里](../blob/master/README.md#faq)
