### ISSUE TITLE
日推的图标日期希望可以跟随真实日期更新

### ISSUE THREAD

**Issue by RangerCD** [gmg137/netease-cloud-music-gtk#311]
**Is your feature request related to a problem? Please describe.**
日推的图标日期目前是一直维持在启动的日期。保持一晚没有关闭，第二天看到的图标仍然是昨天的，但点进去后内容已经是新一天的歌单。此时无论如何操作都无法更新图标日期，只有重新启动才是正确的图标。

**Describe the solution you'd like**
第二天查看日推时图标自动更新成最新日期。

**Describe alternatives you've considered**
有手动刷新的方式也可以。

**Additional context**
![2024-11-01_09-40](https://github.com/user-attachments/assets/7d369e7c-b4e7-4067-a7b4-60c5732fa572)

**Comment by gmg137** [comment]
已修复
