### ISSUE TITLE
加个私人fm功能？

### ISSUE THREAD

**Issue by FengLiuFeseliud** [gmg137/netease-cloud-music-gtk#316]
这个功能挺常用的，不知道能不加一个
接口为 `/api/v1/radio/get` 带上 cookie 就行
一次请求可以返回三首歌

使用例:
https://github.com/FengLiuFeseliud/CloudMusic-Mod/blob/main/src/main/java/fengliu/cloudmusic/music163/data/My.java

**Comment by FengLiuFeseliud** [comment]
少了这个找歌有点不方便了

**Comment by FengLiuFeseliud** [comment]
少了这个找歌有点不方便了，我在 java 用的这个接口挺稳的

**Comment by gmg137** [comment]
Duplicate of #260
