### ISSUE TITLE
喜欢音乐之后在「喜欢的音乐」中没有

### ISSUE THREAD

**Issue by Azureki** [gmg137/netease-cloud-music-gtk#33]
喜欢几个音乐，只有第一个在「喜欢的音乐」中可以看到。
但是用官方版，发现这几个音乐全都有。也就是说其实「喜欢」这个动作是正常的。
我以为是需要刷新，于是关闭应用再打开，但还是只有第一个点击喜欢的音乐。

（顺便请求个feature，已喜欢的音乐能不能用实心的❤显示？

**Comment by gmg137** [comment]
请依次尝试如下解决方案：
1、将第一个音乐右键取消收藏，看其它几个是否会显示出来。（我不确定网易云的接口对返回的音乐数量是否有限制）
2、把已经收藏的音乐取消再重新收藏，看是否可以正常显示出来。
3、把无法显示的歌曲链接或id发给我。

（对于已喜欢的音乐原本我是想要用实心显示的，但发现网易云官方也是当作未收藏来处理，可能这块处理比较麻烦，没有专门的接口判断是否已经收藏）

**Comment by Azureki** [comment]
@gmg137 感谢回复。今天再打开发现都显示了（没有别的操作）。

看来果然是没有刷新？
