### ISSUE TITLE
单曲循环会莫名其妙调到其他歌上

### ISSUE THREAD

**Issue by ExiaHan** [gmg137/netease-cloud-music-gtk#34]
指定歌单某首歌单曲循环的时候有一定概率会跳到随机的歌曲上。 
比较抱歉没有Log，因为从shell启动也没看到有log打出来。

OS: Arch Linux
Version: 0.7.0

**Comment by gmg137** [comment]
测试该问题出现比较随机，有时会播放一半时候出现自动切换，暂时未找到原因。

**Comment by updater1234** [comment]
遇到类似的问题，歌单内循环播放会播放歌单外的歌曲。
