### ISSUE TITLE
Linuxmint 19.2安装deb包，程序打开无反应。

### ISSUE THREAD

**Issue by linghuye** [gmg137/netease-cloud-music-gtk#35]
Linuxmint 19.2 Cinnamon桌面，安装0.7版本deb包，程序打开无反应。

**Comment by linghuye** [comment]
命令行运行，报告错误：
netease-cloud-music-gtk: error while loading shared libraries: libgstplayer-1.0.so.0: cannot open shared object file: No such file or directory
apt也找不到 libgstplayer 依赖包。

**Comment by gmg137** [comment]
把 gstreamer1.0-plugins-bad，gstreamer1.0-plugins-good，gstreamer1.0-plugins-base 装上再试试。

**Comment by linghuye** [comment]
确是这个原因，装 libgstreamer-plugins-bad包解决了。
