### ISSUE TITLE
歌单最多1000首歌

### ISSUE THREAD

**Issue by byrChen** [gmg137/netease-cloud-music-gtk#36]
某个歌单有1400+的歌，对比了一下1001到之后的都没有

**Comment by gmg137** [comment]
我接口写死了歌单最大只获取1000首歌曲，数量可以改，不过不确定这样的需求是否普遍。

**Comment by byrChen** [comment]
这样子，应该不是普遍需求。。还有请问这个在线听的码率怎么设置？是按照用户的设置播放的吗？

**Comment by gmg137** [comment]
码率默认设置的是320k，现在网速不是问题，应该没人会选128的，就没添加相关设置选项。

**Comment by Rigil-Kentaurus** [comment]
如果想获取多于一千首的歌曲该在哪里修改呢……

**Comment by gmg137** [comment]
@Rigil-Kentaurus 在 src/musicapi/mod.rs 文件的第230行

![2019-10-26 08-38-52 的屏幕截图](https://user-images.githubusercontent.com/6460323/67611450-59977d00-f7cc-11e9-9099-6371d2c63e33.png)

**Comment by Rigil-Kentaurus** [comment]
> @Rigil-Kentaurus 在 src/musicapi/mod.rs 文件的第230行
> 
> ![2019-10-26 08-38-52 的屏幕截图](https://user-images.githubusercontent.com/6460323/67611450-59977d00-f7cc-11e9-9099-6371d2c63e33.png)

THX！

**Comment by rocka** [comment]
其实这样是不行的，因为 weapi 这个接口限死了只能获取前 1000 首歌， limit 和 offset 写多大都没用。

网易云官方应用的做法是，获取歌单信息的时候，会顺带返回一个歌曲 id 列表，需要加载大于 1000 首以上的歌曲时，再把 id 列表 post 到获取歌曲信息的接口，拿到以后再进行展示。

**Comment by gmg137** [comment]
@rocka 多谢提醒，这问题之前也发现了，一直不知道怎么解决。

**Comment by Mackel123** [comment]
桌面歌词没有显示……个人的云盘解析错误、喜欢的歌曲和个人歌单都没有
