### ISSUE TITLE
Fedora无法安装

### ISSUE THREAD

**Issue by liyepan** [gmg137/netease-cloud-music-gtk#42]
问题: conflicting requests
  - nothing provides gstreamer needed by netease-cloud-music-gtk-0.7.0-1.x86_64
  - nothing provides gstreamer-plugins-good needed by netease-cloud-music-gtk-0.7.0-1.x86_64
  - nothing provides gstreamer-plugins-libav needed by netease-cloud-music-gtk-0.7.0-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
应该是gstreamer依赖问题,但是fedora无法安装这些依赖包,希望可以提供一些帮助

**Comment by gmg137** [comment]
fedora 下的 gstreamer 的包名不太一样，应该类似这样：gstreamer1-plugins-good

**Comment by PsiACE** [comment]
即便安装了正确的包也无法成功使用 `sudo dnf localinstall netease-cloud-music-gtk-1.1.3-1.x86_64.rpm` 完成安装。

@liyepan  请在安装正确的 `gstreamer1` 开头的对应包之后使用 `sudo rpm -i netease-cloud-music-gtk-1.1.3-1.x86_64.rpm --nodeps` 进行安装。

@gmg137  我个人认为这里可能存在依赖检测问题。

**Comment by system-thoughts** [comment]
> fedora 下的 gstreamer 的包名不太一样，应该类似这样：gstreamer1-plugins-good

对, fedora下的 包不一样，这里应该需要适配下fedora下的安装依赖就ok了

**Comment by system-thoughts** [comment]
@gmg137 源码中能否把spec文件也放进去，我尝试适配下fedora的构建

**Comment by gmg137** [comment]
可以参考下 openSUSE 的 spec 文件， https://build.opensuse.org/package/show/home:gmg137/netease-cloud-music-gtk4

**Comment by system-thoughts** [comment]
> 可以参考下 openSUSE 的 spec 文件， https://build.opensuse.org/package/show/home:gmg137/netease-cloud-music-gtk4

ok，我尝试下~

**Comment by Zsbyqx20** [comment]
fedora下可以在自带的应用市场里用flatpak安装的

**Comment by zippermonkey** [comment]
fedora所需要的依赖包名：
dbus-devel 
glib2-devel
gdk-pixbuf2-devel
gtk4-devel
libadwaita-devel
gstreamer1-plugins-base-devel
gstreamer1-plugins-base-devel
gstreamer1-devel
