### ISSUE TITLE
内存占用较高，有内存泄漏问题

### ISSUE THREAD

**Issue by fplust** [gmg137/netease-cloud-music-gtk#44]
拿valgrind测了下，有内存泄漏问题，不清楚是gtk-rs库的问题，还是 Rc 没用好导致循环引用了。。
你有什么头绪吗？
[valgrind-out.txt](https://github.com/gmg137/netease-cloud-music-gtk/files/3850164/valgrind-out.txt)

**Comment by gmg137** [comment]
之前测试过连续跑一天后观察内存占用，没有发现明显变化。最近更新比较多，我再好好测测。

**Comment by gmg137** [comment]
测试确实有内存泄漏，每点一次首页歌单就会有明显的内存占用增加。应该是程序有问题，还没找到原因。

**Comment by gmg137** [comment]
根据你发的 valgrind 文件，好像是 sled 的问题。

**Comment by fgheng** [comment]
rust也有内存泄漏么？

**Comment by gmg137** [comment]
已完成异步重构，之前“内存泄漏”问题多半是操作系统优化多线程造成的，目前实测保持在60M左右。
