### ISSUE TITLE
关于Rust封装为.deb和.rpm的linux程序

### ISSUE THREAD

**Issue by liyepan** [gmg137/netease-cloud-music-gtk#45]
请教大神一些问题，因为我是一个rust的初学者，我想做linux软件，但是一直找不到关于rust做的程序如何打包为linux软件的相关资料，请问大神可否指点一些，再此谢谢了！

**Comment by gmg137** [comment]
我是用的 cargo-rpm 和 cargo-deb 打包的，在 crates.io 可以搜一下看官方的文档。或者可以参考我这个项目下的 Cargo.toml 中关于 deb 的配置和 .rpm 是关于rpm包的配置。

rust 编译出的直接就是二进制可执行文件，不打包直接拷到PATH目录其实更简单。如果要从源码打包到发行版的仓库，可以参考ripgrep 在各个发行版下的配置，不过具体我也没研究过。。
