### ISSUE TITLE
[Feature request] volume bar and mini mode

### ISSUE THREAD

**Issue by tuberry** [gmg137/netease-cloud-music-gtk#46]
[Arch/gnome3.34]分应用调节音量的插件挂了，希望加个音量条。还有就是增加一个迷你模式。Thanks!

**Comment by gmg137** [comment]
这两个需求我先研究下看好不好实现。。。我也是gnome， 现在是配了几个全局快捷键控制音量和播放。

**Comment by Titubery** [comment]
😸️回复好快。还有我对`关闭至后台运行`这个选项有点疑问，好像没有起到后台运行的作用（最小化是指会被隐藏但用`Alt+Tab`仍能切换到）：
 <table>
     <tr>
          <td>操作\状态</td>
         <td>on</td>
         <td>off</td>
     </tr>
     <tr>
         <td>点击关闭</td>
         <td>退出</td>
         <td>退出</td>
     </tr>
     <tr>
         <td>点击❎️ </td>
         <td>最小化</td>
         <td>最小化</td>
     </tr> 
 </table>
Thanks!!  @gmg137

**Comment by gmg137** [comment]
@Titubery 因为 GNOME 已经取消托盘，所以如果真的关闭到后台，可能会造成很多麻烦，所以我这里的关闭到后台是使用的最小化。

**Comment by Titubery** [comment]
据说是wayland不支持托盘gnome干脆取消了。关闭到后台其实可以像网易云那样点击顶栏通知区域唤出，mini模式部分也是为了避免切换窗口时出现。这个暂时可以移动到其他的workspace避免切换到。另能不能增加记住历史的功能，比如上次听的歌单和循环模式之类的，每次打开都要切歌单换模式，不然听一首就停了。还有我不能把它设为默认播放器，是因为没有实现播放本地文件的功能吗？ @gmg137

**Comment by gmg137** [comment]
记住播放模式这个简单，我这两天有空了加上。

不能设默认播放器这个回头研究下，gnome官方的 gnome-music 也不能，但 totem 就可以。

**Comment by Titubery** [comment]
谢谢，还有我想在已登录的情况下默认打开`我的`页面比较方便，当然这个也可以改成记住。gnome-music的问题好像是不能打开`~/Music`之外的音乐文件所以不能作为默认播放器 @gmg137

**Comment by gmg137** [comment]
音量条已添加。

**Comment by tuberry** [comment]
>  音量条已添加。

谢谢！有点小瑕疵：可以记住音量但重启后音量显示不对（显示满音量
![volume](https://user-images.githubusercontent.com/17917040/74538022-34469e80-4f76-11ea-8d12-fad5ac06ccbc.png)

**Comment by gmg137** [comment]
事实上重启后无法获取之前的音量，参考 totem 现在已经改为重启直接静音了。

**Comment by tuberry** [comment]
totem 重启可以记住音量显示也没有问题。直接静音反而不太方便，这样每次打开点播放后还要拉一下音量条。

**Comment by gmg137** [comment]
已增加记住音量功能。

**Comment by tuberry** [comment]
能不能支持下 [Mpris2](https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Property:LoopStatus) 的 [loopStatus](https://docs.rs/mpris/1.1.2/mpris/enum.LoopStatus.html)？按照 [Mpris Indicator Button](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/User-Guide) 的说法，控件可见一般就是可用的，但实际上点击循环按钮并不会改变  netease-cloud-music-gtk 的状态。
![image](https://user-images.githubusercontent.com/17917040/81515618-89246600-9367-11ea-97d0-0a6bb42c0d3f.png)

**Comment by gmg137** [comment]
应该可以，等下个版本添加上去。

________________________________


能不能支持下 Mpris2<https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Property:LoopStatus> 的 loopStatus<https://docs.rs/mpris/1.1.2/mpris/enum.LoopStatus.html>？按照 Mpris Indicator Button<https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/User-Guide> 的说法，控件可见一般就是可用的，但实际上点击循环按钮并不会改变 netease-cloud-music-gtk 的状态。
[image]<https://user-images.githubusercontent.com/17917040/81515618-89246600-9367-11ea-97d0-0a6bb42c0d3f.png>

―

**Comment by tuberry** [comment]
新的版本测试没问题，不知道[TrackList](https://docs.rs/mpris/2.0.0-rc1/mpris/struct.TrackList.html)能不能安排一下？
