### ISSUE TITLE
no `ModelButton` in the root

### ISSUE THREAD

**Issue by stokhos** [gmg137/netease-cloud-music-gtk#47]
Running `rustc --edition=2018 --crate-name netease_cloud_music_gtk src/main.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' -C metadata=24827ce9788306f2 -C extra-filename=-24827ce9788306f2 --out-dir /home/ginstok/netease-cloud-music-gtk/target/release/deps -L dependency=/home/ginstok/netease-cloud-music-gtk/target/release/deps --extern base64=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libbase64-8046f572f47d903e.rlib --extern cairo=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libcairo-5ca6c2ca7da1cfa0.rlib --extern cargo_rpm=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libcargo_rpm-7bccaf2f67c86f23.rlib --extern chrono=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libchrono-4ef84debef0fcb2f.rlib --extern crossbeam_channel=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libcrossbeam_channel-e60691a059aa0001.rlib --extern curl=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libcurl-8b05675ab228085f.rlib --extern dbus=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libdbus-7066be00c81cae45.rlib --extern dirs=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libdirs-ad73f8d890d4d347.rlib --extern fragile=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libfragile-5532fa872a0886ee.rlib --extern gdk=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgdk-94a9dd396bae5355.rlib --extern gdk_pixbuf=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgdk_pixbuf-b40d5d68e9c36ee4.rlib --extern gio=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgio-e4207120db77b41d.rlib --extern glib=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libglib-82b95b7ef6b0183c.rlib --extern gstreamer=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgstreamer-75889c0806cc1abb.rlib --extern gstreamer_player=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgstreamer_player-988b3a4ca8e464ae.rlib --extern gtk=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgtk-e4e09c33f129a330.rlib --extern hex=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libhex-30dd79951e141cc8.rlib --extern image=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libimage-5028c1449e1f5190.rlib --extern lazy_static=/home/ginstok/netease-cloud-music-gtk/target/release/deps/liblazy_static-0563ed23a1c1397b.rlib --extern log=/home/ginstok/netease-cloud-music-gtk/target/release/deps/liblog-6c38d6de68a057a0.rlib --extern loggerv=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libloggerv-439ac4f8caaf81df.rlib --extern mpris_player=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libmpris_player-a192218a6d73fea0.rlib --extern num=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libnum-cf3b9874fdf87e7f.rlib --extern openssl=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libopenssl-4e273d4230cfb049.rlib --extern pango=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libpango-03d504252ae743a5.rlib --extern rand=/home/ginstok/netease-cloud-music-gtk/target/release/deps/librand-3d543717b617c2fe.rlib --extern rayon=/home/ginstok/netease-cloud-music-gtk/target/release/deps/librayon-6c6819706e5b977b.rlib --extern regex=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libregex-ea3366ad85cf21c7.rlib --extern serde=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libserde-388f67f0c08eaca5.rlib --extern serde_json=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libserde_json-625d29226271119b.rlib --extern serde_urlencoded=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libserde_urlencoded-aae499be3e312959.rlib --extern sled=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libsled-565bc947efb14616.rlib -L native=/home/ginstok/netease-cloud-music-gtk/target/release/build/backtrace-sys-cf07384d63c50288/out -L native=/usr/lib/x86_64-linux-gnu -L native=/home/ginstok/netease-cloud-music-gtk/target/release/build/curl-sys-0d2925c192f63276/out/build -L native=/usr/lib/x86_64-linux-gnu`
error[E0432]: unresolved import `gtk::ModelButton`
  --> src/widgets/header.rs:17:76
   |
17 |     AboutDialog, Builder, Button, Dialog, Entry, Image, Label, MenuButton, ModelButton, Popover, SearchBar,
   |                                                                            ^^^^^^^^^^^
   |                                                                            |
   |                                                                            no `ModelButton` in the root
   |                                                                            help: a similar name exists in the module: `ToolButton`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `netease-cloud-music-gtk`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name netease_cloud_music_gtk src/main.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' -C metadata=24827ce9788306f2 -C extra-filename=-24827ce9788306f2 --out-dir /home/ginstok/netease-cloud-music-gtk/target/release/deps -L dependency=/home/ginstok/netease-cloud-music-gtk/target/release/deps --extern base64=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libbase64-8046f572f47d903e.rlib --extern cairo=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libcairo-5ca6c2ca7da1cfa0.rlib --extern cargo_rpm=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libcargo_rpm-7bccaf2f67c86f23.rlib --extern chrono=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libchrono-4ef84debef0fcb2f.rlib --extern crossbeam_channel=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libcrossbeam_channel-e60691a059aa0001.rlib --extern curl=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libcurl-8b05675ab228085f.rlib --extern dbus=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libdbus-7066be00c81cae45.rlib --extern dirs=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libdirs-ad73f8d890d4d347.rlib --extern fragile=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libfragile-5532fa872a0886ee.rlib --extern gdk=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgdk-94a9dd396bae5355.rlib --extern gdk_pixbuf=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgdk_pixbuf-b40d5d68e9c36ee4.rlib --extern gio=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgio-e4207120db77b41d.rlib --extern glib=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libglib-82b95b7ef6b0183c.rlib --extern gstreamer=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgstreamer-75889c0806cc1abb.rlib --extern gstreamer_player=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgstreamer_player-988b3a4ca8e464ae.rlib --extern gtk=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libgtk-e4e09c33f129a330.rlib --extern hex=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libhex-30dd79951e141cc8.rlib --extern image=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libimage-5028c1449e1f5190.rlib --extern lazy_static=/home/ginstok/netease-cloud-music-gtk/target/release/deps/liblazy_static-0563ed23a1c1397b.rlib --extern log=/home/ginstok/netease-cloud-music-gtk/target/release/deps/liblog-6c38d6de68a057a0.rlib --extern loggerv=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libloggerv-439ac4f8caaf81df.rlib --extern mpris_player=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libmpris_player-a192218a6d73fea0.rlib --extern num=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libnum-cf3b9874fdf87e7f.rlib --extern openssl=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libopenssl-4e273d4230cfb049.rlib --extern pango=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libpango-03d504252ae743a5.rlib --extern rand=/home/ginstok/netease-cloud-music-gtk/target/release/deps/librand-3d543717b617c2fe.rlib --extern rayon=/home/ginstok/netease-cloud-music-gtk/target/release/deps/librayon-6c6819706e5b977b.rlib --extern regex=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libregex-ea3366ad85cf21c7.rlib --extern serde=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libserde-388f67f0c08eaca5.rlib --extern serde_json=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libserde_json-625d29226271119b.rlib --extern serde_urlencoded=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libserde_urlencoded-aae499be3e312959.rlib --extern sled=/home/ginstok/netease-cloud-music-gtk/target/release/deps/libsled-565bc947efb14616.rlib -L native=/home/ginstok/netease-cloud-music-gtk/target/release/build/backtrace-sys-cf07384d63c50288/out -L native=/usr/lib/x86_64-linux-gnu -L native=/home/ginstok/netease-cloud-music-gtk/target/release/build/curl-sys-0d2925c192f63276/out/build -L native=/usr/lib/x86_64-linux-gnu` (exit code: 1)

On ubuntu 19.10,  rustc 1.39

**Comment by fplust** [comment]
```bash
cargo build --features gtk_3_24
```
