### ISSUE TITLE
登录异常，无法登陆

### ISSUE THREAD

**Issue by ImKujio** [gmg137/netease-cloud-music-gtk#49]
如题，我尝试命令行启动软件没看到错误信息，找遍/usr/ ~/.config/ ~/.cache/ /tmp/都没有log文件，所以我也不知道是什么导致的，环境是Manjaro+i3，
邮箱地址：imkujio@qq.com

**Comment by gmg137** [comment]
目前接口只支持网易邮箱账号或与邮箱绑定的手机号登陆，不支持其它账号登陆。

**Comment by ImKujio** [comment]
> 目前接口只支持网易邮箱账号或与邮箱绑定的手机号登陆，不支持其它账号登陆。

我是手机号，但是不知道有没有绑定邮箱，必须得要与邮箱绑定吗

**Comment by ImKujio** [comment]
> 目前接口只支持网易邮箱账号或与邮箱绑定的手机号登陆，不支持其它账号登陆。

我绑定了邮箱，之后就可以登陆了，感谢。
