### ISSUE TITLE
版本：请求分配一个新的 tag 0.7.1

### ISSUE THREAD

**Issue by LionNatsu** [gmg137/netease-cloud-music-gtk#52]
您好！这里是 AOSC OS 发行版的维护者。
我们在打包 0.7.0 的时候遇到了困难 https://github.com/AOSC-Dev/aosc-os-abbs/issues/2051 ，我留意到紧随其后 #37 提供的构建系统方面修正的提交 df4c5a97cb43ae3ccc73f9841d695643da31a214 中已经修复了这个问题。
建议分配一个 0.7.1 版本给这个提交节点，这将大大方便发行版流水线打包这个版本。

**Comment by gmg137** [comment]
因为想在1.0前用异步做个重构，所以最近没什么更新，明天可以先打个标签

**Comment by gmg137** [comment]
已发0.8.0版本
