### ISSUE TITLE
0.8.1 进入后提示网络异常，但 0.8.0 不会

### ISSUE THREAD

**Issue by eatradish** [gmg137/netease-cloud-music-gtk#55]
环境：AOSC OS ( `Linux eat-x230 5.4.6-aosc-main #1 SMP Sat Dec 21 12:36:00 UTC 2019 x86_64 GNU/Linux`) + NetworkManager(`1.18.0`)

**Comment by gmg137** [comment]
0.8.0升0.8.1也需要删除旧配置文件，这是升级上游依赖 sled 版本造成的。
