### ISSUE TITLE
播放模式选择随机，然后点击下一首会卡顿

### ISSUE THREAD

**Issue by fgheng** [gmg137/netease-cloud-music-gtk#59]
在我的音乐中，播放模式选择随机播放，然后选择下一首，此时会卡顿一会。
而且我发现好像不能随机，一直就那两手歌在随机来随机去

**Comment by gmg137** [comment]
点击下一首会先把下一首歌下载后才播放，如果网速慢的话是可能会有卡顿的。

随机播放测试了，没有问题。
