### ISSUE TITLE
arch kde打不开

### ISSUE THREAD

**Issue by kktt007** [gmg137/netease-cloud-music-gtk#6]
有截图，打开图标转几下就没了
https://img.vim-cn.com/72/4c5dd23e22f199d98dc6cf3c3fdfbfe53b8a9f.jpg

**Comment by gmg137** [comment]
从命令行运行，看报什么错？

**Comment by lan542662** [comment]
好了，缺少Glibc_2.29 这是testing仓库的，现在打开有问题，不能播放，登录错误，首页很小。
https://img.vim-cn.com/a9/7fb1d389bcd804e0f55ea2efd18ca357d96ec9.png
https://img.vim-cn.com/d2/b86cfcdfd12658db92ea8d89e546b5c5c32bc6.png
https://img.vim-cn.com/01/37b29a83e898a430ee3167f08d13bc6538ab13.png
https://img.vim-cn.com/2a/0137403a49759eec1566851a59752ad3b020af.png

**Comment by gmg137** [comment]
> 不能播放，请检查下面几个包是否已经安装:
```
gstreamer1.0-plugins-base
gstreamer1.0-plugins-good 
gstreamer1.0-plugins-bad
gstreamer1.0-plugins-ugly
gstreamer1.0-libav
```

> 登陆错误一般是网易检测到登陆异常造成的，可以先在网页登陆以后，再登陆试试。

> 首页很小，看截图你用的应该不是 GNOME 桌面，猜测是 arch 只安装 gtk 核心包，许多推荐的包没有安装造成的。这个没有测试条件，只能靠你自己了。
