### ISSUE TITLE
界面设计建议

### ISSUE THREAD

**Issue by fgheng** [gmg137/netease-cloud-music-gtk#60]
如果这首音乐已经添加到我的喜欢的音乐中了，那么最好这个心能点亮，要不然我不知道当前这首歌是不是我喜爱的音乐。
![image](https://user-images.githubusercontent.com/50551377/72305533-10f6ae00-36af-11ea-8291-3c014839d5a1.png)

**Comment by gmg137** [comment]
这个问题在设计之初就有考虑过，实现需要增加网络请求次数，可能会影响界面流畅度。后来看了官方客户端，发现也是不显示收藏状态，所以就把这个功能取消了。
