### ISSUE TITLE
专辑相关设计

### ISSUE THREAD

**Issue by slikie** [gmg137/netease-cloud-music-gtk#63]
可能和作者听歌习惯不一样吧，有些人是以专辑形式听歌的，而不是歌单形式。

希望能有这些和原生应用的行为

- 搜索时能选择专辑（歌手）
- 查看当前播放歌曲的专辑（歌手）
- （按选定的循环方式）播放整张专辑

**Comment by gmg137** [comment]
2.0 版本已加入专辑搜索、播放功能。
