### ISSUE TITLE
您好，想请问一下，您的单曲图片是怎样获取的？

### ISSUE THREAD

**Issue by qianyigengwu** [gmg137/netease-cloud-music-gtk#67]
您的单曲图片是如何获取的呢？是有固定的URL吗？
假设现在我拿到了单曲ID，如何根据ID获取图片？

**Comment by gmg137** [comment]
在获取歌单的列表信息中会包含歌曲专辑图片地址，或者可以根据歌曲ID查询歌曲的信息，里边也有包含。
