### ISSUE TITLE
没有KDE托盘？

### ISSUE THREAD

**Issue by abcfy2** [gmg137/netease-cloud-music-gtk#68]
作者你好，我是在Majaro KDE桌面环境下运行，我发现勾选关闭到后台的时候，并没有托盘出现在KDE托盘区，用命令行运行也没有也没有发现任何错误，这是什么情况？能否修复呢？

**Comment by gmg137** [comment]
#31 GNOME3/GTK3 已经不再支持系统托盘，暂时可以通过点击应用图标或媒体控件来重新唤醒程序和控制播放。

**Comment by abcfy2** [comment]
好的，明白了，多谢作者。话说rust静态编译确实不错，依赖很轻
