### ISSUE TITLE
多首特定音乐只能播放1分钟29秒

### ISSUE THREAD

**Issue by Laoyian** [gmg137/netease-cloud-music-gtk#70]
OS：Ubuntu 18.04
版本：1.1.0
网络：移动
现象：多首音乐进度条只有1分钟29秒左右（时间不等），之后自动跳到下一首歌曲，且这些歌曲在网页或Android客户端上播放没有问题。

**Comment by Laoyian** [comment]
有趣的是，把有问题的歌曲的本地缓存删除之后再播放就恢复正常了，以上复现步骤已经不能复原，推测可能是网络的原因，建议下载歌曲后对比播放时长是否相同。

**Comment by gmg137** [comment]
正在缓存音乐的时候关闭程序是有可能造成音乐文件损坏的，几率应该很小，回头研究下看怎么解决。
________________________________

**Comment by Laoyian** [comment]
可以在缓存时使用专门的文件名，等下载完再重命名。
