### ISSUE TITLE
无法播放歌曲数目大于651的歌单

### ISSUE THREAD

**Issue by Laoyian** [gmg137/netease-cloud-music-gtk#71]
版本： 1.1.0
现象：歌曲数目大于651的歌单，点击右上角的播放按钮没有反应，无法播放。

复现步骤：播放含有652首及以上歌曲的歌单。
测试歌单 https://music.163.com/#/my/m/music/playlist?id=4956550632

**Comment by gmg137** [comment]
刚测试了播放没问题

**Comment by Laoyian** [comment]
> 刚测试了播放没问题

我重新测试了一下，发现1.0.0没有这个问题，而1.1.0的deb包在我的 ubuntu 18.04 和 debian testing 上没法通过右上角播放歌单，因为编译出错了我没有测试是不是打包的问题。

**Comment by reee** [comment]
我这里是直接无法打开歌曲数目太多的歌单，另外界面很漂亮，666

**Comment by gmg137** [comment]
把无法打开的歌单链接发出来，我测试下。


---

我这里是直接无法打开歌曲数目太多的歌单，另外界面很漂亮，666

**Comment by reee** [comment]
http://t.cn/A6wvG6GL
我这个只有400多首。打开提示数据解析异常。
操作系统是manjaro 安装的archlinuxcn里面预编译的包。

**Comment by Laoyian** [comment]
> http://t.cn/A6wvG6GL
> 我这个只有400多首。打开提示数据解析异常。
> 操作系统是manjaro 安装的archlinuxcn里面预编译的包。

你的歌单在我这里可以正常播放。

**Comment by gmg137** [comment]
@reee 我测试也没问题。

有时候打开歌单空白可能是网络问题，多等上几秒就好了。
