### ISSUE TITLE
ubuntu18安装提示libgstplayer-1.0.so.0找不到，求snap

### ISSUE THREAD

**Issue by rexlevin** [gmg137/netease-cloud-music-gtk#72]
两台ubuntu18，一台可以，一台不行，下载的netease-cloud-music-gtk-ubuntu_18.04_1.1.0_amd64.deb，安装正常完成，启动不成功，终端下启动提示：netease-cloud-music-gtk: error while loading shared libraries: libgstplayer-1.0.so.0: cannot open shared object file: No such file or directory，不知道这个问题应该手动安装什么依赖？
可以话求推入snapcraft，这样更方便吧，谢谢。

**Comment by gmg137** [comment]
看项目说明，把 gstreamer 相关依赖装上就行了。
