### ISSUE TITLE
歌单中双击播放显示无法播放，点击歌单播放正常

### ISSUE THREAD

**Issue by HougeLangley** [gmg137/netease-cloud-music-gtk#73]
系统是 Manjaro，安装途径是 Archlinuxcn 源，双击播放歌曲显示出错，但是歌单整个播放就正常了。

**Comment by gmg137** [comment]
这是1.1.0版本的bug，已经修复，可以自行编译或者等发新版本

**Comment by HougeLangley** [comment]
> 这是1.1.0版本的bug，已经修复，可以自行编译或者等发新版本

感谢，现目前等待更新就好
