### ISSUE TITLE
archlinux和manjaro上默认静音

### ISSUE THREAD

**Issue by qianyigengwu** [gmg137/netease-cloud-music-gtk#74]
每次网易云GTK启动时，无论播放什么歌曲，都是默认静音的，不清楚原因，KDE和Gnome上都有。

**Comment by gmg137** [comment]
这是一种取舍，默认静音是为了防止在公众场合突然外放造成可能的尴尬。

**Comment by gmg137** [comment]
已增加记住音量功能，将在下个版本发布
