### ISSUE TITLE
无法读取“我喜欢的音乐”

### ISSUE THREAD

**Issue by qianyigengwu** [gmg137/netease-cloud-music-gtk#77]
其他歌单都正常，一到“我喜欢的音乐”就“数据请求失败”

**Comment by gmg137** [comment]
1、换1.1.1版本。
2、删除数据目录。
> ```rm $HOME/.local/share/netease-cloud-music-gtk/*```

3、如果还不行就把你的歌单分享出来我调试下。

**Comment by uiYzzi** [comment]
> 1，换1.1.1版本
> 。2，删除数据目录。
> 
> > `rm $HOME/.local/share/netease-cloud-music-gtk/*`
> 
> 3，如果还不行就把你的歌单分享出来我调试下。

我的也是这样，歌单链接：http://music.163.com/#/m/playlist?id=4988091142

**Comment by gmg137** [comment]
@uiYzzi 我测试播放没有问题。

你试下双击播放单首歌曲看是否正常?

**Comment by uiYzzi** [comment]
> @uiYzzi我测试播放没有问题。
> 
> 你试下双击播放单首歌曲看是否正常？

我的是直接歌单打不开，而且只有这个歌单是这样，其他都是正常

**Comment by uiYzzi** [comment]
> @uiYzzi我测试播放没有问题。
> 
> 你试下双击播放单首歌曲看是否正常？

我可能大概知道为什么了？我上传到音乐云盘的歌是网易曲库没有的，所以获取不到音乐id？

**Comment by gmg137** [comment]
应该不是，我这里上传云盘的音乐都可以正常播放。

一般提示解析失败是无法获取歌单或歌单返回的格式有误造成的。我明天单独给你打包个带调试信息的，你运行下看是哪里问题。

**Comment by uiYzzi** [comment]
> 一般提示解析失败是无法获取歌单或歌单返回的格式有误造成的。我明天单独给你打包个带调试信息的，你运行下看是哪里问题。

好的，谢谢

**Comment by gmg137** [comment]
@uiYzzi  https://send.firefox.com/download/1b18daf17fbf60c2/#ZkySf-la-Iy71f7PLaVJGQ

**Comment by uiYzzi** [comment]
> @uiYzzi https://send.firefox.com/download/1b18daf17fbf60c2/#ZkySf-la-Iy71f7PLaVJGQ
> 
> 从命令行启动，然后选择有问题的歌单，把终端输出的内容贴出来。

歌单名称: 柚柚的!!!
歌单详情:
{"code":200,"relatedVideos":null,"playlist":{"subscribers":[],"subscribed":false,"creator":{"defaultAvatar":false,"province":150000,"authStatus":0,"followed":false,"avatarUrl":"http://p1.music.126.net/5EB5bprhtXWGW2rNb8vVNQ==/109951164930980609.jpg","accountStatus":0,"gender":2,"city":150900,"birthday":975728240351,"userId":1505985634,"userType":0,"nickname":"花祭笙","signature":"善解人意不可能了。","description":"","detailDescription":"","avatarImgId":109951164930980609,"backgroundImgId":109951164930982936,"backgroundUrl":"http://p1.music.126.net/xUyoDFA07rwkIYcOPI0lCA==/109951164930982936.jpg","authority":0,"mutual":false,"expertTags":null,"experts":null,"djStatus":0,"vipType":0,"remarkName":null,"avatarImgIdStr":"109951164930980609","backgroundImgIdStr":"109951164930982936","avatarImgId_str":"109951164930980609"},"tracks":[{"name":"改天再忙","id":465921641,"pst":0,"t":0,"ar":[{"id":1047139,"name":"RAiNBOW计划","tns":[],"alias":[]},{"id":27729963,"name":"林力尧","tns":[],"alias":[]}],"alia":[],"pop":100.0,"st":0,"rt":null,"fee":8,"v":18,"crbt":null,"cf":"","al":{"id":35288185,"name":"黄","picUrl":"http://p2.music.126.net/yRgTfVXGbey72ou_49CtVA==/18931391207076094.jpg","tns":[],"pic_str":"18931391207076094","pic":18931391207076094},"dt":252089,"h":{"br":320000,"fid":0,"size":10086444,"vd":-5400.0},"m":{"br":192000,"fid":0,"size":6051884,"vd":-2700.0},"l":{"br":128000,"fid":0,"size":4034604,"vd":-800.0},"a":null,"cd":"1","no":9,"rtUrl":null,"ftype":0,"rtUrls":[],"djId":0,"copyright":2,"s_id":0,"mark":64,"originCoverType":0,"noCopyrightRcmd":null,"mst":9,"cp":22036,"mv":5810755,"rtype":0,"rurl":null,"publishTime":1489939200007},{"name":"阍者","id":514761125,"pst":0,"t":0,"ar":[{"id":5001,"name":"简弘亦","tns":[],"alias":[]}],"alia":[],"pop":100.0,"st":0,"rt":null,"fee":8,"v":22,"crbt":null,"cf":"","al":{"id":37026227,"name":"柔软的国","picUrl":"http://p2.music.126.net/Nm9VNrN0oE9kmPPyxTomoA==/109951163742438662.jpg","tns":[],"pic_str":"109951163742438662","pic":109951163742438662},"dt":296331,"h":{"br":320000,"fid":0,"size":11855456,"vd":-10599.0},"m":{"br":192000,"fid":0,"size":7113291,"vd":-8100.0},"l":{"br":128000,"fid":0,"size":4742208,"vd":-6300.0},"a":null,"cd":"01","no":5,"rtUrl":null,"ftype":0,"rtUrls":[],"djId":0,"copyright":2,"s_id":0,"mark":64,"originCoverType":0,"noCopyrightRcmd":null,"mst":9,"cp":740012,"mv":0,"rtype":0,"rurl":null,"publishTime":1508774400007},{"name":"没那么简单","id":239188,"pst":0,"t":0,"ar":[{"id":7896,"name":"黄小琥","tns":[],"alias":[]}],"alia":[],"pop":100.0,"st":0,"rt":"600902000008838030","fee":1,"v":40,"crbt":null,"cf":"","al":{"id":23974,"name":"简单/不简单","picUrl":"http://p2.music.126.net/U0dHDI2p0qE6pj_G5sNA2Q==/109951163188719906.jpg","tns":[],"pic_str":"109951163188719906","pic":109951163188719906},"dt":308000,"h":{"br":320000,"fid":0,"size":12327749,"vd":-27000.0},"m":{"br":192000,"fid":0,"size":7396666,"vd":-24400.0},"l":{"br":128000,"fid":0,"size":4931125,"vd":-22800.0},"a":null,"cd":"1","no":2,"rtUrl":null,"ftype":0,"rtUrls":[],"djId":0,"copyright":1,"s_id":0,"mark":8192,"originCoverType":0,"noCopyrightRcmd":null,"mst":9,"cp":7002,"mv":58469,"rtype":0,"rurl":null,"publishTime":1261065600000},{"name":"像鱼","id":1331819951,"pst":0,"t":0,"ar":[{"id":14312549,"name":"王贰浪","tns":[],"alias":[]}],"alia":[],"pop":100.0,"st":0,"rt":null,"fee":8,"v":13,"crbt":null,"cf":"","al":{"id":74793881,"name":"像鱼","picUrl":"http://p2.music.126.net/ejEPGN6ulPSgCBXGq7dgqw==/109951163720047382.jpg","tns":[],"pic_str":"109951163720047382","pic":109951163720047382},"dt":285271,"h":{"br":320000,"fid":0,"size":11413464,"vd":-1.0},"m":{"br":192000,"fid":0,"size":6848096,"vd":0.0},"l":{"br":128000,"fid":0,"size":4565412,"vd":0.0},"a":null,"cd":"1","no":1,"rtUrl":null,"ftype":0,"rtUrls":[],"djId":0,"copyright":0,"s_id":0,"mark":65536,"originCoverType":0,"noCopyrightRcmd":null,"mst":9,"cp":1415874,"mv":0,"rtype":0,"rurl":null,"publishTime":1544457600000},{"name":"留声机 （Aceboom第五届专场主题曲）","id":1370179774,"pst":0,"t":0,"ar":[{"id":13156257,"name":"颜枫林","tns":[],"alias":[]},{"id":30712575,"name":"Hazy李好","tns":[],"alias":[]},{"id":12128363,"name":"谢若曲","tns":[],"alias":[]}],"alia":[],"pop":95.0,"st":0,"rt":"","fee":8,"v":9,"crbt":null,"cf":"","al":{"id":79564511,"name":"留声机—AceBoom街舞第五届专场主题曲","picUrl":"http://p2.music.126.net/6SyTNKz8c09kkyTy75a4sw==/109951164129364220.jpg","tns":[],"pic_str":"109951164129364220","pic":109951164129364220},"dt":293112,"h":{"br":320000,"fid":0,"size":11726933,"vd":-38756.0},"m":{"br":192000,"fid":0,"size":7036177,"vd":-36138.0},"l":{"br":128000,"fid":0,"size":4690799,"vd":-34390.0},"a":null,"cd":"01","no":1,"rtUrl":null,"ftype":0,"rtUrls":[],"djId":0,"copyright":0,"s_id":0,"mark":64,"originCoverType":0,"noCopyrightRcmd":null,"mst":9,"cp":0,"mv":0,"rtype":0,"rurl":null,"publishTime":0},{"name":"像我这样的人","id":569213220,"pst":0,"t":0,"ar":[{"id":12138269,"name":"毛不易","tns":[],"alias":[]}],"alia":[],"pop":100.0,"st":0,"rt":null,"fee":8,"v":100,"crbt":null,"cf":"","al":{"id":39483040,"name":"平凡的一天","picUrl":"http://p2.music.126.net/vmCcDvD1H04e9gm97xsCqg==/109951163350929740.jpg","tns":[],"pic_str":"109951163350929740","pic":109951163350929740},"dt":207466,"h":{"br":320000,"fid":0,"size":8301758,"vd":-2.0},"m":{"br":192000,"fid":0,"size":4981072,"vd":-2.0},"l":{"br":128000,"fid":0,"size":3320729,"vd":-2.0},"a":null,"cd":"2","no":1,"rtUrl":null,"ftype":0,"rtUrls":[],"djId":0,"copyright":2,"s_id":0,"mark":8192,"originCoverType":0,"noCopyrightRcmd":null,"mst":9,"cp":755014,"mv":5959041,"rtype":0,"rurl":null,"publishTime":1530547200007},{"name":"慢冷","id":1365650668,"pst":0,"t":1,"ar":[{"id":0,"name":null,"tns":[],"alias":[]}],"alia":[],"pop":0.0,"st":0,"rt":null,"fee":0,"v":8,"crbt":null,"cf":null,"al":{"id":0,"name":null,"picUrl":"http://p2.music.126.net/UeTuwE7pvjBpypWLudqukA==/3132508627578625.jpg","tns":[],"pic":0},"dt":289645,"h":null,"m":null,"l":{"br":320032,"fid":0,"size":11587000,"vd":0.0},"a":null,"cd":null,"no":0,"rtUrl":null,"ftype":0,"rtUrls":[],"djId":0,"copyright":0,"s_id":0,"mark":0,"originCoverType":0,"noCopyrightRcmd":null,"mst":9,"cp":0,"mv":0,"rtype":0,"rurl":null,"publishTime":0,"pc":{"nickname":"","fn":"3179517112.mp3","uid":1505985634,"cid":"","alb":"我好吗？－太阳如常升起","ar":"梁静茹","sn":"慢冷","br":320,"version":1}}],"trackIds":[{"id":465921641,"v":18,"alg":null},{"id":514761125,"v":22,"alg":null},{"id":239188,"v":40,"alg":null},{"id":1331819951,"v":13,"alg":null},{"id":1370179774,"v":9,"alg":null},{"id":569213220,"v":100,"alg":null},{"id":1365650668,"v":7,"alg":null}],"updateFrequency":null,"backgroundCoverId":0,"backgroundCoverUrl":null,"titleImage":0,"titleImageUrl":null,"englishTitle":null,"opRecommend":false,"adType":0,"trackNumberUpdateTime":1588680380888,"tags":[],"userId":1505985634,"highQuality":false,"trackCount":6,"playCount":2,"coverImgUrl":"http://p1.music.126.net/yRgTfVXGbey72ou_49CtVA==/18931391207076094.jpg","createTime":1588680132482,"trackUpdateTime":1588695694056,"updateTime":1588680380888,"newImported":false,"coverImgId":18931391207076094,"specialType":0,"commentThreadId":"A_PL_0_5004529101","privacy":0,"description":null,"subscribedCount":0,"cloudTrackCount":1,"ordered":false,"status":0,"name":"柚柚的最爱(๑°3°๑)!!!","id":5004529101,"shareCount":0,"coverImgId_str":"18931391207076094","commentCount":0},"urls":null,"privileges":[{"id":465921641,"fee":8,"payed":0,"st":0,"pl":128000,"dl":0,"sp":7,"cp":1,"subp":1,"cs":false,"maxbr":999000,"fl":128000,"toast":false,"flag":258,"preSell":false,"playMaxbr":999000,"downloadMaxbr":999000},{"id":514761125,"fee":8,"payed":0,"st":0,"pl":128000,"dl":0,"sp":7,"cp":1,"subp":1,"cs":false,"maxbr":999000,"fl":128000,"toast":false,"flag":2,"preSell":false,"playMaxbr":999000,"downloadMaxbr":999000},{"id":239188,"fee":1,"payed":0,"st":0,"pl":0,"dl":0,"sp":0,"cp":0,"subp":0,"cs":false,"maxbr":999000,"fl":0,"toast":false,"flag":1028,"preSell":false,"playMaxbr":999000,"downloadMaxbr":999000},{"id":1331819951,"fee":8,"payed":0,"st":0,"pl":128000,"dl":0,"sp":7,"cp":1,"subp":1,"cs":false,"maxbr":999000,"fl":128000,"toast":false,"flag":0,"preSell":false,"playMaxbr":999000,"downloadMaxbr":999000},{"id":1370179774,"fee":8,"payed":0,"st":0,"pl":128000,"dl":0,"sp":7,"cp":1,"subp":1,"cs":false,"maxbr":999000,"fl":128000,"toast":false,"flag":66,"preSell":false,"playMaxbr":999000,"downloadMaxbr":999000},{"id":569213220,"fee":8,"payed":0,"st":0,"pl":128000,"dl":0,"sp":7,"cp":1,"subp":1,"cs":false,"maxbr":999000,"fl":128000,"toast":false,"flag":68,"preSell":false,"playMaxbr":999000,"downloadMaxbr":999000},{"id":1365650668,"fee":0,"payed":0,"st":0,"pl":320000,"dl":320000,"sp":0,"cp":0,"subp":1,"cs":true,"maxbr":96000,"fl":999000,"toast":false,"flag":136,"preSell":false,"playMaxbr":0,"downloadMaxbr":0}]}

**Comment by gmg137** [comment]
@uiYzzi 问题已经修复，是因为包含的音乐没有歌手信息造成的解析错误。

下载这个临时救急: https://send.firefox.com/download/d4e62a28a1b0d7ea/#Rfwv7vu8HQEvdJCk1lk5NQ

**Comment by uiYzzi** [comment]
ok,谢谢啦



在 2020-05-07 09:40:31，"gmg137" <notifications@github.com> 写道：

@uiYzzi 问题已经修复，是因为包含的音乐没有歌手信息造成的解析错误。

下载这个临时救急: https://send.firefox.com/download/d4e62a28a1b0d7ea/#Rfwv7vu8HQEvdJCk1lk5NQ

**Comment by uiYzzi** [comment]
> @uiYzzi问题已经修复，是因为包含的音乐没有歌手信息造成的解析错误。
> 
> 下载这个临时救急：[https](https://send.firefox.com/download/8e52011a59cc134a/#Z5-QgoZvtggCsXPPCOtqmA) ://send.firefox.com/download/8e52011a59cc134a/#Z5-QgoZvtggCsXPPCOtqmA[](https://send.firefox.com/download/8e52011a59cc134a/#Z5-QgoZvtggCsXPPCOtqmA)

可以用啦！谢谢
