### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by koyangyang** [gmg137/netease-cloud-music-gtk#78]
安装完第一次使用，就提示数据解析失败，界面全是白色啥也没有，也无法登录，登录提示登录异常

**Comment by gmg137** [comment]
这是账号异常登陆造成的，你先在浏览器上登陆网易云音乐，做点常规操作，然后再重新打开 netease-cloud-music-gtk 登陆试试能否解决。

**Comment by koyangyang** [comment]
刚试着在浏览器听了一会，再打开软件还是首页，发现页提示数据解析异常。还是无法登录，提示登录异常

**Comment by gmg137** [comment]
你安装的是哪个版本？？

 登陆的话只支持网易邮箱登陆或者绑定邮箱的手机号登陆。

**Comment by koyangyang** [comment]
我用的是ubantu的deb包，我系统是deepin，我用的手机号登录

**Comment by gmg137** [comment]
确认下手机号是否已经绑定网易邮箱，然后从命令行启动程序看是否有报错。
