### ISSUE TITLE
求一个32位的deb安装包

### ISSUE THREAD

**Issue by pasv0001** [gmg137/netease-cloud-music-gtk#79]
如题，用的是老机器，ubuntu14.06LTS，编译安装不成功，gstreamer版本太低，能否给打包个32位的版本，谢谢啦！

**Comment by gmg137** [comment]
你说的是 16.04 吧?

因为依赖于上游的 gstreamer 库，要求 1.0 以上版本，所以版本太低的问题基本无解。
