### ISSUE TITLE
Ubuntu20.04下运行错误

### ISSUE THREAD

**Issue by wikylyu** [gmg137/netease-cloud-music-gtk#85]
我拉取了项目的最新代码

```
commit 8021da38649b59e425d9c8a7c392589c511a1b52 (HEAD -> master, origin/master, origin/HEAD)
Author: gmg137 <gmg137@live.com>
Date:   Sat May 16 23:05:47 2020 +0800

    - 增加Mpris退出控制.
    - 修复拼写错误.
```

在Ubuntu20.04下编译成功，并且能运行程序。但运行后提示以下错误

![Screenshot from 2020-05-26 21-00-21](https://user-images.githubusercontent.com/65841899/82903764-04a32b80-9f94-11ea-9327-546aa0a68a9f.png)

我的rust版本是

```
cargo --version
cargo 1.43.0 (2cbe9048e 2020-05-03)
```

**Comment by gmg137** [comment]
```RUST_BACKTRACE=full cargo run```
运行上边命令把输出贴出来。

**Comment by wikylyu** [comment]
我发现在公司电脑上(Ubuntu19.10)是没有问题的，代码和cargo版本都是一样的。晚上回家了把BACKTRACE打印出来看看。

**Comment by gmg137** [comment]
已经确认是上游 async-std 1.6 版本的问题，临时解决方案可以修改 Cargo.toml 文件，固定 async-std 版本号。
```
async-std = "~1.5"
```

重新编译
```
cargo update
cargo build --release
```

**Comment by wikylyu** [comment]
@gmg137 确实可以了
