### ISSUE TITLE
有些歌曲时间不对

### ISSUE THREAD

**Issue by zerohk** [gmg137/netease-cloud-music-gtk#86]
有些歌曲显示时长是三四分钟，但实际播放时间只有一分半左右，进度条也只显示一分多钟

**Comment by gmg137** [comment]
清下缓存应该就好了
```
rm -rf ~/.cache/netease-cloud-music-gtk/*
```

确认下你的版本是否为最新版本，理论上不应该再出现你说的情况。

**Comment by zerohk** [comment]
> 清下缓存应该就好了
> 
> ```
> rm -rf ~/.cache/netease-cloud-music-gtk/*
> ```
> 
> 确认下你的版本是否为最新版本，理论上不应该再出现你说的情况。

刷新列表后好像没出现了，谢谢

**Comment by gmg137** [comment]
到云音乐上看看是不是版权问题
