### ISSUE TITLE
[Bug] Pressing Space button will pause/play the music while typing in the search box

### ISSUE THREAD

**Issue by whriedplanck** [gmg137/netease-cloud-music-gtk#87]
OS: Arch Linux
DE: KDE Plasma 5.19 (Same issue occurred on MATE 1.24) 
Software Version: 1.1.2

**Comment by gmg137** [comment]
这其实是早期程序版本中内置的快捷键，以后可能会删除。
| 快捷键 | 功能 |
| ------- | ------ |
| 空格 | 播放/暂停 |
| Ctrl + n | 下一曲 |
| Ctrl + b | 上一曲 | 

如果需要搜索可以使用 "+" 号代替空格。

**Comment by whriedplanck** [comment]
> 这其实是早期程序版本中内置的快捷键，以后可能会删除。
> 快捷键 	功能
> 空格 	播放/暂停
> Ctrl + n 	下一曲
> Ctrl + b 	上一曲
> 
> 如果需要搜索可以使用 "+" 号代替空格。

原来如此啊，谢谢解答～！（问到了给 Arch 打包的 Maintainer，他还说居然有搜索功能 …… QwQ）
