### ISSUE TITLE
有部分歌曲只加载一部分的情况

### ISSUE THREAD

**Issue by bladelei** [gmg137/netease-cloud-music-gtk#88]
我好几首歌听着听着忽然跳下一首，一开始以为是没播完就跳了，后来对比了手机端才发现是这个情况：一首歌在手机端（正常）是４分半，然后电脑上rust网易云里面时长只有３分半了

**Comment by bladelei** [comment]
系统是:manjaro kde,刚发现几乎所有的歌的时长都变成了3分半左右

**Comment by gmg137** [comment]
#86 你们估计是一个原因造成的，清理下缓存试试。

**Comment by bladelei** [comment]
多谢，问题解决了，确实和#86一样

**Comment by bladelei** [comment]
> #86 你们估计是一个原因造成的，清理下缓存试试。

谢谢你，问题解决了，确实和#86一样
