### ISSUE TITLE
登录异常

### ISSUE THREAD

**Issue by eatradish** [gmg137/netease-cloud-music-gtk#9]
用户名填写的是手机号 (没有 +86)，已经在网页上登录过

环境：AOSC OS + KDE + networkmanager，网络正常，对于此程序没有挂代理 (在国内)，netease-cloud-music-gtk 使用了 rust nightly 1.36 编译

**Comment by eatradish** [comment]
log 没有相关输出

**Comment by gmg137** [comment]
@eatradish 用邮箱登陆试试，这里使用的手机号登陆接口貌似只支持邮箱绑定的手机号(直接手机号注册的不支持)。

**Comment by mrsun-97** [comment]
> @eatradish 用邮箱登陆试试，这里使用的手机号登陆接口貌似只支持邮箱绑定的手机号(直接手机号注册的不支持)。

我刚刚也遇到了这个问题，绑定网易邮箱用邮箱登录的确可行

**Comment by Sam0523** [comment]
没有绑定邮箱的用户，除了注册网易邮箱绑定以外还有别的办法吗
