### ISSUE TITLE
ProgressBar 太大了，能不能缩小一些

### ISSUE THREAD

**Issue by onlymash** [gmg137/netease-cloud-music-gtk#90]
如图
![Screenshot from 2020-07-10 19-02-03](https://user-images.githubusercontent.com/5838634/87147912-0759a600-c2e0-11ea-8a65-d932d4f654e6.png)

**Comment by gmg137** [comment]
在我的电脑上显示是正常的。。。说下你的操作系统、桌面环境、应用版本。

**Comment by onlymash** [comment]
@gmg137 archlinux gnome 3.36.4

**Comment by gmg137** [comment]
程序的版本呢？？

是从archlinux-cn源安装的还是运行的 appimage？

**Comment by onlymash** [comment]
早已经编辑了回复 你刷新一下。 cn源安装的

**Comment by gmg137** [comment]
已修复

**Comment by onlymash** [comment]
编译了最新版，还是一样的问题
![image](https://user-images.githubusercontent.com/5838634/96666532-e6e2c280-1389-11eb-82aa-e9485506475b.png)

**Comment by onlymash** [comment]
gtk 主题 mojave

**Comment by gmg137** [comment]
我已经设置 ProgressBar 为固定大小了，感觉是你gtk环境配置问题，你先换回默认主题试试。

**Comment by onlymash** [comment]
默认主题还是一样的

**Comment by gmg137** [comment]
直接到GTK的项目下提问试试，我这块完全没思路
