### ISSUE TITLE
添加 Proxy 設定功能

### ISSUE THREAD

**Issue by junyussh** [gmg137/netease-cloud-music-gtk#93]
人在海外，有些音樂有版權地區限制，需要透過代理才能聽，希望能添加設定 Socks5, HTTP 的代理功能

**Comment by gmg137** [comment]
应该可以实现，下个版本加上。
________________________________

**Comment by sky5454** [comment]
> 人在海外，有些音樂有版權地區限制，需要透過代理才能聽，希望能添加設定 Socks5, HTTP 的代理功能

本程序会强制使用 http_ptoxy https_proxy两个变量作为代理 所以你只要先在终端设置这两个变量，从该终端启动本程序即可

**Comment by gmg137** [comment]
2.0 版本已加入代理功能
