### ISSUE TITLE
Ubuntu 20.04编译完成但运行失败

### ISSUE THREAD

**Issue by suiahae** [gmg137/netease-cloud-music-gtk#94]
### 复现步骤
按照README的步骤进行编译，编译完成无报错.
```bash
$ cargo build --release

    Updating crates.io index
  Downloaded gstreamer-player v0.16.0
   ...
   Compiling async-std v1.6.3
   ...
   Compiling netease-cloud-music-gtk v1.1.2 (/home/ubtuee/Downloads/netease-cloud-music-gtk)
    Finished release [optimized] target(s) in 11m 41s
```
### 错误结果
但打包安装后发现无法使用，页面无法加载：
![image](https://user-images.githubusercontent.com/45323123/90742658-16ca0700-e302-11ea-8572-6621bed0aeda.png)
![image](https://user-images.githubusercontent.com/45323123/90743155-382af300-e302-11ea-996c-05a3c59f64b7.png)

从命令行启动播放器，会显示报错信息：
```bash
$ ./netease-cloud-music-gtk 
thread 'async-std/runtime' panicked at 'cannot call `Executor::enter()` if already inside an `Executor`', /builddir/build/BUILD/rustc-1.45.2-src/src/libstd/macros.rs:13:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'async-std/runtime' panicked at 'cannot call `Executor::enter()` if already inside an `Executor`', /builddir/build/BUILD/rustc-1.45.2-src/src/libstd/macros.rs:13:23
```
### 补充信息
1. 在async-std仓库的issue区找到了类似的问题：https://github.com/async-rs/async-std/issues/795 ("Cannot run an executor inside another executor" - in tests)，开发者提交的更改 https://github.com/async-rs/async-std/pull/799 称已解决此问题 https://github.com/async-rs/async-std/issues/795 。「疑惑」
2. 目前可以使用的只有`netease-cloud-music-gtk-ubuntu_18.04_1.1.2_amd64.deb`和它内部的可执行文件`netease-cloud-music-gtk`，新编译的无法正常运行。编译失败的原因大概率为async-std等依赖项的更新导致的。

祝好

**Comment by gmg137** [comment]
这应该是 async-std 1.6.3 新引入的 bug，临时解决可以修改Cargo.toml，把 async-std 的依赖版本改为 "=1.6.2"

**Comment by suiahae** [comment]
> 这应该是 async-std 1.6.3 新引入的 bug，临时解决可以修改Cargo.toml，把 async-std 的依赖版本改为 "=1.6.2"

改过就可以了。但为什在Cargo.toml中依赖项版本写成"^version"，而不是更稳定的"=version"呀

**Comment by gmg137** [comment]
理论上 1.6.* 这种小版本号的更新不会改动 api，可以直接升级，但因为上游smol改动过大造成现在的问题。

**Comment by suiahae** [comment]
明白了

**Comment by gmg137** [comment]
问题已修复
