### ISSUE TITLE
不能用鼠标后退键返回上一页面

### ISSUE THREAD

**Issue by yueduz** [gmg137/netease-cloud-music-gtk#96]
![20200518094308_7931cbfda006b64bcceea5698ce6646c_1](https://user-images.githubusercontent.com/1448159/92320113-93264f00-f051-11ea-8aa8-90cece232a16.jpeg)

只能点左上角的按钮返回。

**Comment by gmg137** [comment]
你测试下，看有没有其它支持该模式的 GTK 应用，我手头没设备无法确定这两个按键会发出什么信号。

**Comment by yueduz** [comment]
gnome 带的文件管理器就能

**Comment by gmg137** [comment]
@yueduz 在命令行下运行这个程序，然后按鼠标上的前进后退键，把输出贴给我

```链接: https://pan.baidu.com/s/1vPgncZS6d0iMFN32mUVO_A 提取码: bam7 复制这段内容后打开百度网盘手机App，操作更方便哦```

**Comment by yueduz** [comment]
![2020-10-14 16-23-09 的屏幕截图](https://user-images.githubusercontent.com/1448159/95962913-945d4f80-0e39-11eb-9386-6580faa6e5cd.png)
没有输出,就一个窗口

**Comment by yueduz** [comment]
![2020-10-14 16-27-44 的屏幕截图](https://user-images.githubusercontent.com/1448159/95963453-4b59cb00-0e3a-11eb-9bff-8d912d17a71c.png)
使用xev检测:后退是8前进是9

**Comment by gmg137** [comment]
搞错了，把抓取鼠标搞成抓取键盘的了。

再试一下
> 链接: [https://pan.baidu.com/s/1yE5uThvv4QK5DoeOHXQZRg](https://pan.baidu.com/s/1yE5uThvv4QK5DoeOHXQZRg) 提取码: ibhd 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by yueduz** [comment]
![2020-10-15 09-09-34 的屏幕截图](https://user-images.githubusercontent.com/1448159/96061574-2c087f80-0ec6-11eb-8e4e-dae66368fcba.png)

**Comment by gmg137** [comment]
试试是否可用，可以的话直接复制到 /usr/bin 中替换原文件就行了。
> 链接: [https://pan.baidu.com/s/1fVIxvBxzM5uESHuZ8jaxCw](https://pan.baidu.com/s/1fVIxvBxzM5uESHuZ8jaxCw )提取码: u5e5 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by yueduz** [comment]
可以用了
