### ISSUE TITLE
gnome桌面歌词无效

### ISSUE THREAD

**Issue by lwgpshit** [gmg137/netease-cloud-music-gtk#97]
如题已经安装了osdlyrics

**Comment by gmg137** [comment]
1、检查osdlyrics 的配置中歌词文件目录是否为 ~/.lyrics。
2、用 gnome-music 播放个本地中文音乐，看osdlyrics 显示歌词是否正常。

**Comment by zzugyl** [comment]
osdlyrics 过时了？我在Ubuntu20.04中apt安装或者自编译安装，都打不开。
提示错误：
`Error*: in function _start_daemon_cb: ol_main.c[768]
Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Daemon exited with status 1`

**Comment by gmg137** [comment]
我用的 openSUSE，目前没有发现你说的问题，建议直接到 [https://github.com/osdlyrics/osdlyrics](https://github.com/osdlyrics/osdlyrics) 反馈

**Comment by lwgpshit** [comment]
我已经解决了。。
