### ISSUE TITLE
多次登录返回错误

### ISSUE THREAD

**Issue by sonichy** [gmg137/netease-cloud-music-gtk#98]
用python (https://blog.forgiveher.cn/2018/12/15/1544852143/) 测试，第一次能登录，忘了记录返回数据，再登录就返回：{"message":"当前登录失败，请稍后再试","code":250}

这样登出又无效
import requests

header = {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36'
}
surl = 'https://music.163.com/weapi/logout'
data = '{}'
response = requests.post(surl, data=data, headers=header)
print(response)

**Comment by gmg137** [comment]
python 登陆你可以参考下：https://github.com/darknessomi/musicbox
