### ISSUE TITLE
在播放時打開搜索框，搜索框中按下空格，會停止歌曲的播放，而不是輸入空格

### ISSUE THREAD

**Issue by eatradish** [gmg137/netease-cloud-music-gtk#99]
版本：1.1.2

**Comment by gmg137** [comment]
这跟打开搜索框没关系，空格是播放暂停的快捷键，ctrl+p和+n是上一首下一首。如果要在搜索中输入空格，可以用+号代替。

**Comment by eatradish** [comment]
我認爲此問題是存在的，而不是「by design」。我有幾個問題：

一、這種不符合常理的用法，似乎沒有任何文檔告知用家，以後會有更多人被「坑到」。
二、當我搜索含有加號的歌曲時，我應該怎麼辦？

**Comment by neruthes** [comment]
盲猜开发者会说可以输入 %2B 来表示加号（

**Comment by MarvelousBlack** [comment]
正常的逻辑应该在搜索框的时候播放的快捷键应该不响应，输入空格就应该是空格，而且在刚开出来还没有音乐播放的时候，确实搜索框是可以输入空格的，所以我觉得这是快捷键捕获的问题。

**Comment by gmg137** [comment]
搜索功能一直都是半成品，原计划是可以按歌曲名、歌手、专辑、歌单等来搜索，因为各种原因一直没有实现。快捷键也只是测试用的，所以没有写入文档。
